//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("RENTECOSAModel", "FK_ApplicationRequest_Customer", "Customer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Nexus.Customer), "ApplicationRequest", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Nexus.ApplicationRequest), true)]
[assembly: EdmRelationshipAttribute("RENTECOSAModel", "FK_ApplicationRequestDetail_ApplicationRequest", "ApplicationRequest", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Nexus.ApplicationRequest), "ApplicationRequestDetail", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Nexus.ApplicationRequestDetail), true)]
[assembly: EdmRelationshipAttribute("RENTECOSAModel", "FK_ApplicationRequestDetail_Measure", "Measure", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Nexus.Measure), "ApplicationRequestDetail", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Nexus.ApplicationRequestDetail), true)]
[assembly: EdmRelationshipAttribute("RENTECOSAModel", "FK_CustomerContact_Customer", "Customer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Nexus.Customer), "CustomerContact", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Nexus.CustomerContact), true)]
[assembly: EdmRelationshipAttribute("RENTECOSAModel", "FK_CustomerProject_Customer", "Customer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Nexus.Customer), "CustomerProject", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Nexus.CustomerProject), true)]
[assembly: EdmRelationshipAttribute("RENTECOSAModel", "FK_CustomerContact_Person", "Person", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Nexus.Person), "CustomerContact", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Nexus.CustomerContact), true)]
[assembly: EdmRelationshipAttribute("RENTECOSAModel", "FK_PersonPhone_Person", "Person", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Nexus.Person), "PersonPhone", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Nexus.PersonPhone), true)]
[assembly: EdmRelationshipAttribute("RENTECOSAModel", "FK_PersonPhone_PhoneType", "PhoneType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Nexus.PhoneType), "PersonPhone", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Nexus.PersonPhone), true)]

#endregion

namespace Nexus
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class RENTECOSAContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new RENTECOSAContext object using the connection string found in the 'RENTECOSAContext' section of the application configuration file.
        /// </summary>
        public RENTECOSAContext() : base("name=RENTECOSAContext", "RENTECOSAContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RENTECOSAContext object.
        /// </summary>
        public RENTECOSAContext(string connectionString) : base(connectionString, "RENTECOSAContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RENTECOSAContext object.
        /// </summary>
        public RENTECOSAContext(EntityConnection connection) : base(connection, "RENTECOSAContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ApplicationRequest> ApplicationRequests
        {
            get
            {
                if ((_ApplicationRequests == null))
                {
                    _ApplicationRequests = base.CreateObjectSet<ApplicationRequest>("ApplicationRequests");
                }
                return _ApplicationRequests;
            }
        }
        private ObjectSet<ApplicationRequest> _ApplicationRequests;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ApplicationRequestDetail> ApplicationRequestDetails
        {
            get
            {
                if ((_ApplicationRequestDetails == null))
                {
                    _ApplicationRequestDetails = base.CreateObjectSet<ApplicationRequestDetail>("ApplicationRequestDetails");
                }
                return _ApplicationRequestDetails;
            }
        }
        private ObjectSet<ApplicationRequestDetail> _ApplicationRequestDetails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Customer> Customers
        {
            get
            {
                if ((_Customers == null))
                {
                    _Customers = base.CreateObjectSet<Customer>("Customers");
                }
                return _Customers;
            }
        }
        private ObjectSet<Customer> _Customers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CustomerContact> CustomerContacts
        {
            get
            {
                if ((_CustomerContacts == null))
                {
                    _CustomerContacts = base.CreateObjectSet<CustomerContact>("CustomerContacts");
                }
                return _CustomerContacts;
            }
        }
        private ObjectSet<CustomerContact> _CustomerContacts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CustomerProject> CustomerProjects
        {
            get
            {
                if ((_CustomerProjects == null))
                {
                    _CustomerProjects = base.CreateObjectSet<CustomerProject>("CustomerProjects");
                }
                return _CustomerProjects;
            }
        }
        private ObjectSet<CustomerProject> _CustomerProjects;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Measure> Measures
        {
            get
            {
                if ((_Measures == null))
                {
                    _Measures = base.CreateObjectSet<Measure>("Measures");
                }
                return _Measures;
            }
        }
        private ObjectSet<Measure> _Measures;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Person> People
        {
            get
            {
                if ((_People == null))
                {
                    _People = base.CreateObjectSet<Person>("People");
                }
                return _People;
            }
        }
        private ObjectSet<Person> _People;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PersonPhone> PersonPhones
        {
            get
            {
                if ((_PersonPhones == null))
                {
                    _PersonPhones = base.CreateObjectSet<PersonPhone>("PersonPhones");
                }
                return _PersonPhones;
            }
        }
        private ObjectSet<PersonPhone> _PersonPhones;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PhoneType> PhoneTypes
        {
            get
            {
                if ((_PhoneTypes == null))
                {
                    _PhoneTypes = base.CreateObjectSet<PhoneType>("PhoneTypes");
                }
                return _PhoneTypes;
            }
        }
        private ObjectSet<PhoneType> _PhoneTypes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ApplicationRequests EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToApplicationRequests(ApplicationRequest applicationRequest)
        {
            base.AddObject("ApplicationRequests", applicationRequest);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ApplicationRequestDetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToApplicationRequestDetails(ApplicationRequestDetail applicationRequestDetail)
        {
            base.AddObject("ApplicationRequestDetails", applicationRequestDetail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Customers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomers(Customer customer)
        {
            base.AddObject("Customers", customer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CustomerContacts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomerContacts(CustomerContact customerContact)
        {
            base.AddObject("CustomerContacts", customerContact);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CustomerProjects EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomerProjects(CustomerProject customerProject)
        {
            base.AddObject("CustomerProjects", customerProject);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Measures EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMeasures(Measure measure)
        {
            base.AddObject("Measures", measure);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the People EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPeople(Person person)
        {
            base.AddObject("People", person);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PersonPhones EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPersonPhones(PersonPhone personPhone)
        {
            base.AddObject("PersonPhones", personPhone);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PhoneTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPhoneTypes(PhoneType phoneType)
        {
            base.AddObject("PhoneTypes", phoneType);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RENTECOSAModel", Name="ApplicationRequest")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ApplicationRequest : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ApplicationRequest object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="customerId">Initial value of the CustomerId property.</param>
        public static ApplicationRequest CreateApplicationRequest(global::System.Int32 id, global::System.Int32 customerId)
        {
            ApplicationRequest applicationRequest = new ApplicationRequest();
            applicationRequest.Id = id;
            applicationRequest.CustomerId = customerId;
            return applicationRequest;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CustomerId
        {
            get
            {
                return _CustomerId;
            }
            set
            {
                OnCustomerIdChanging(value);
                ReportPropertyChanging("CustomerId");
                _CustomerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CustomerId");
                OnCustomerIdChanged();
            }
        }
        private global::System.Int32 _CustomerId;
        partial void OnCustomerIdChanging(global::System.Int32 value);
        partial void OnCustomerIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RENTECOSAModel", "FK_ApplicationRequest_Customer", "Customer")]
        public Customer Customer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("RENTECOSAModel.FK_ApplicationRequest_Customer", "Customer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("RENTECOSAModel.FK_ApplicationRequest_Customer", "Customer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Customer> CustomerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("RENTECOSAModel.FK_ApplicationRequest_Customer", "Customer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Customer>("RENTECOSAModel.FK_ApplicationRequest_Customer", "Customer", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RENTECOSAModel", "FK_ApplicationRequestDetail_ApplicationRequest", "ApplicationRequestDetail")]
        public EntityCollection<ApplicationRequestDetail> ApplicationRequestDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ApplicationRequestDetail>("RENTECOSAModel.FK_ApplicationRequestDetail_ApplicationRequest", "ApplicationRequestDetail");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ApplicationRequestDetail>("RENTECOSAModel.FK_ApplicationRequestDetail_ApplicationRequest", "ApplicationRequestDetail", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RENTECOSAModel", Name="ApplicationRequestDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ApplicationRequestDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ApplicationRequestDetail object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="applicationRequestId">Initial value of the ApplicationRequestId property.</param>
        /// <param name="measureId">Initial value of the MeasureId property.</param>
        /// <param name="quantity">Initial value of the Quantity property.</param>
        /// <param name="problem">Initial value of the Problem property.</param>
        /// <param name="solution">Initial value of the Solution property.</param>
        public static ApplicationRequestDetail CreateApplicationRequestDetail(global::System.Int32 id, global::System.Int32 applicationRequestId, global::System.Int32 measureId, global::System.Double quantity, global::System.String problem, global::System.String solution)
        {
            ApplicationRequestDetail applicationRequestDetail = new ApplicationRequestDetail();
            applicationRequestDetail.Id = id;
            applicationRequestDetail.ApplicationRequestId = applicationRequestId;
            applicationRequestDetail.MeasureId = measureId;
            applicationRequestDetail.Quantity = quantity;
            applicationRequestDetail.Problem = problem;
            applicationRequestDetail.Solution = solution;
            return applicationRequestDetail;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ApplicationRequestId
        {
            get
            {
                return _ApplicationRequestId;
            }
            set
            {
                OnApplicationRequestIdChanging(value);
                ReportPropertyChanging("ApplicationRequestId");
                _ApplicationRequestId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ApplicationRequestId");
                OnApplicationRequestIdChanged();
            }
        }
        private global::System.Int32 _ApplicationRequestId;
        partial void OnApplicationRequestIdChanging(global::System.Int32 value);
        partial void OnApplicationRequestIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MeasureId
        {
            get
            {
                return _MeasureId;
            }
            set
            {
                OnMeasureIdChanging(value);
                ReportPropertyChanging("MeasureId");
                _MeasureId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MeasureId");
                OnMeasureIdChanged();
            }
        }
        private global::System.Int32 _MeasureId;
        partial void OnMeasureIdChanging(global::System.Int32 value);
        partial void OnMeasureIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                OnQuantityChanging(value);
                ReportPropertyChanging("Quantity");
                _Quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quantity");
                OnQuantityChanged();
            }
        }
        private global::System.Double _Quantity;
        partial void OnQuantityChanging(global::System.Double value);
        partial void OnQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Problem
        {
            get
            {
                return _Problem;
            }
            set
            {
                OnProblemChanging(value);
                ReportPropertyChanging("Problem");
                _Problem = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Problem");
                OnProblemChanged();
            }
        }
        private global::System.String _Problem;
        partial void OnProblemChanging(global::System.String value);
        partial void OnProblemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Solution
        {
            get
            {
                return _Solution;
            }
            set
            {
                OnSolutionChanging(value);
                ReportPropertyChanging("Solution");
                _Solution = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Solution");
                OnSolutionChanged();
            }
        }
        private global::System.String _Solution;
        partial void OnSolutionChanging(global::System.String value);
        partial void OnSolutionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RENTECOSAModel", "FK_ApplicationRequestDetail_ApplicationRequest", "ApplicationRequest")]
        public ApplicationRequest ApplicationRequest
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ApplicationRequest>("RENTECOSAModel.FK_ApplicationRequestDetail_ApplicationRequest", "ApplicationRequest").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ApplicationRequest>("RENTECOSAModel.FK_ApplicationRequestDetail_ApplicationRequest", "ApplicationRequest").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ApplicationRequest> ApplicationRequestReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ApplicationRequest>("RENTECOSAModel.FK_ApplicationRequestDetail_ApplicationRequest", "ApplicationRequest");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ApplicationRequest>("RENTECOSAModel.FK_ApplicationRequestDetail_ApplicationRequest", "ApplicationRequest", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RENTECOSAModel", "FK_ApplicationRequestDetail_Measure", "Measure")]
        public Measure Measure
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Measure>("RENTECOSAModel.FK_ApplicationRequestDetail_Measure", "Measure").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Measure>("RENTECOSAModel.FK_ApplicationRequestDetail_Measure", "Measure").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Measure> MeasureReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Measure>("RENTECOSAModel.FK_ApplicationRequestDetail_Measure", "Measure");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Measure>("RENTECOSAModel.FK_ApplicationRequestDetail_Measure", "Measure", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RENTECOSAModel", Name="Customer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Customer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Customer object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="address">Initial value of the Address property.</param>
        public static Customer CreateCustomer(global::System.Int32 id, global::System.String name, global::System.String address)
        {
            Customer customer = new Customer();
            customer.Id = id;
            customer.Name = name;
            customer.Address = address;
            return customer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RENTECOSAModel", "FK_ApplicationRequest_Customer", "ApplicationRequest")]
        public EntityCollection<ApplicationRequest> ApplicationRequests
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ApplicationRequest>("RENTECOSAModel.FK_ApplicationRequest_Customer", "ApplicationRequest");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ApplicationRequest>("RENTECOSAModel.FK_ApplicationRequest_Customer", "ApplicationRequest", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RENTECOSAModel", "FK_CustomerContact_Customer", "CustomerContact")]
        public EntityCollection<CustomerContact> CustomerContacts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CustomerContact>("RENTECOSAModel.FK_CustomerContact_Customer", "CustomerContact");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CustomerContact>("RENTECOSAModel.FK_CustomerContact_Customer", "CustomerContact", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RENTECOSAModel", "FK_CustomerProject_Customer", "CustomerProject")]
        public EntityCollection<CustomerProject> CustomerProjects
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CustomerProject>("RENTECOSAModel.FK_CustomerProject_Customer", "CustomerProject");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CustomerProject>("RENTECOSAModel.FK_CustomerProject_Customer", "CustomerProject", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RENTECOSAModel", Name="CustomerContact")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CustomerContact : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CustomerContact object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="job">Initial value of the Job property.</param>
        /// <param name="personId">Initial value of the PersonId property.</param>
        /// <param name="customerId">Initial value of the CustomerId property.</param>
        public static CustomerContact CreateCustomerContact(global::System.Int32 id, global::System.String job, global::System.Int32 personId, global::System.Int32 customerId)
        {
            CustomerContact customerContact = new CustomerContact();
            customerContact.Id = id;
            customerContact.Job = job;
            customerContact.PersonId = personId;
            customerContact.CustomerId = customerId;
            return customerContact;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Job
        {
            get
            {
                return _Job;
            }
            set
            {
                OnJobChanging(value);
                ReportPropertyChanging("Job");
                _Job = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Job");
                OnJobChanged();
            }
        }
        private global::System.String _Job;
        partial void OnJobChanging(global::System.String value);
        partial void OnJobChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PersonId
        {
            get
            {
                return _PersonId;
            }
            set
            {
                OnPersonIdChanging(value);
                ReportPropertyChanging("PersonId");
                _PersonId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PersonId");
                OnPersonIdChanged();
            }
        }
        private global::System.Int32 _PersonId;
        partial void OnPersonIdChanging(global::System.Int32 value);
        partial void OnPersonIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CustomerId
        {
            get
            {
                return _CustomerId;
            }
            set
            {
                OnCustomerIdChanging(value);
                ReportPropertyChanging("CustomerId");
                _CustomerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CustomerId");
                OnCustomerIdChanged();
            }
        }
        private global::System.Int32 _CustomerId;
        partial void OnCustomerIdChanging(global::System.Int32 value);
        partial void OnCustomerIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RENTECOSAModel", "FK_CustomerContact_Customer", "Customer")]
        public Customer Customer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("RENTECOSAModel.FK_CustomerContact_Customer", "Customer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("RENTECOSAModel.FK_CustomerContact_Customer", "Customer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Customer> CustomerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("RENTECOSAModel.FK_CustomerContact_Customer", "Customer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Customer>("RENTECOSAModel.FK_CustomerContact_Customer", "Customer", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RENTECOSAModel", "FK_CustomerContact_Person", "Person")]
        public Person Person
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Person>("RENTECOSAModel.FK_CustomerContact_Person", "Person").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Person>("RENTECOSAModel.FK_CustomerContact_Person", "Person").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Person> PersonReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Person>("RENTECOSAModel.FK_CustomerContact_Person", "Person");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Person>("RENTECOSAModel.FK_CustomerContact_Person", "Person", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RENTECOSAModel", Name="CustomerProject")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CustomerProject : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CustomerProject object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="customerId">Initial value of the CustomerId property.</param>
        public static CustomerProject CreateCustomerProject(global::System.Int32 id, global::System.String name, global::System.Int32 customerId)
        {
            CustomerProject customerProject = new CustomerProject();
            customerProject.Id = id;
            customerProject.Name = name;
            customerProject.CustomerId = customerId;
            return customerProject;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CustomerId
        {
            get
            {
                return _CustomerId;
            }
            set
            {
                OnCustomerIdChanging(value);
                ReportPropertyChanging("CustomerId");
                _CustomerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CustomerId");
                OnCustomerIdChanged();
            }
        }
        private global::System.Int32 _CustomerId;
        partial void OnCustomerIdChanging(global::System.Int32 value);
        partial void OnCustomerIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RENTECOSAModel", "FK_CustomerProject_Customer", "Customer")]
        public Customer Customer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("RENTECOSAModel.FK_CustomerProject_Customer", "Customer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("RENTECOSAModel.FK_CustomerProject_Customer", "Customer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Customer> CustomerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("RENTECOSAModel.FK_CustomerProject_Customer", "Customer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Customer>("RENTECOSAModel.FK_CustomerProject_Customer", "Customer", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RENTECOSAModel", Name="Measure")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Measure : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Measure object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Measure CreateMeasure(global::System.Int32 id, global::System.String name)
        {
            Measure measure = new Measure();
            measure.Id = id;
            measure.Name = name;
            return measure;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RENTECOSAModel", "FK_ApplicationRequestDetail_Measure", "ApplicationRequestDetail")]
        public EntityCollection<ApplicationRequestDetail> ApplicationRequestDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ApplicationRequestDetail>("RENTECOSAModel.FK_ApplicationRequestDetail_Measure", "ApplicationRequestDetail");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ApplicationRequestDetail>("RENTECOSAModel.FK_ApplicationRequestDetail_Measure", "ApplicationRequestDetail", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RENTECOSAModel", Name="Person")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Person : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Person object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        public static Person CreatePerson(global::System.Int32 id, global::System.String name, global::System.String lastName)
        {
            Person person = new Person();
            person.Id = id;
            person.Name = name;
            person.LastName = lastName;
            return person;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RENTECOSAModel", "FK_CustomerContact_Person", "CustomerContact")]
        public EntityCollection<CustomerContact> CustomerContacts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CustomerContact>("RENTECOSAModel.FK_CustomerContact_Person", "CustomerContact");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CustomerContact>("RENTECOSAModel.FK_CustomerContact_Person", "CustomerContact", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RENTECOSAModel", "FK_PersonPhone_Person", "PersonPhone")]
        public EntityCollection<PersonPhone> PersonPhones
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PersonPhone>("RENTECOSAModel.FK_PersonPhone_Person", "PersonPhone");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PersonPhone>("RENTECOSAModel.FK_PersonPhone_Person", "PersonPhone", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RENTECOSAModel", Name="PersonPhone")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PersonPhone : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PersonPhone object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="phone">Initial value of the Phone property.</param>
        /// <param name="phoneTypeId">Initial value of the PhoneTypeId property.</param>
        /// <param name="personId">Initial value of the PersonId property.</param>
        public static PersonPhone CreatePersonPhone(global::System.Int32 id, global::System.String phone, global::System.Int32 phoneTypeId, global::System.Int32 personId)
        {
            PersonPhone personPhone = new PersonPhone();
            personPhone.Id = id;
            personPhone.Phone = phone;
            personPhone.PhoneTypeId = phoneTypeId;
            personPhone.PersonId = personId;
            return personPhone;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PhoneTypeId
        {
            get
            {
                return _PhoneTypeId;
            }
            set
            {
                OnPhoneTypeIdChanging(value);
                ReportPropertyChanging("PhoneTypeId");
                _PhoneTypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PhoneTypeId");
                OnPhoneTypeIdChanged();
            }
        }
        private global::System.Int32 _PhoneTypeId;
        partial void OnPhoneTypeIdChanging(global::System.Int32 value);
        partial void OnPhoneTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PersonId
        {
            get
            {
                return _PersonId;
            }
            set
            {
                OnPersonIdChanging(value);
                ReportPropertyChanging("PersonId");
                _PersonId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PersonId");
                OnPersonIdChanged();
            }
        }
        private global::System.Int32 _PersonId;
        partial void OnPersonIdChanging(global::System.Int32 value);
        partial void OnPersonIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RENTECOSAModel", "FK_PersonPhone_Person", "Person")]
        public Person Person
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Person>("RENTECOSAModel.FK_PersonPhone_Person", "Person").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Person>("RENTECOSAModel.FK_PersonPhone_Person", "Person").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Person> PersonReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Person>("RENTECOSAModel.FK_PersonPhone_Person", "Person");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Person>("RENTECOSAModel.FK_PersonPhone_Person", "Person", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RENTECOSAModel", "FK_PersonPhone_PhoneType", "PhoneType")]
        public PhoneType PhoneType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PhoneType>("RENTECOSAModel.FK_PersonPhone_PhoneType", "PhoneType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PhoneType>("RENTECOSAModel.FK_PersonPhone_PhoneType", "PhoneType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PhoneType> PhoneTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PhoneType>("RENTECOSAModel.FK_PersonPhone_PhoneType", "PhoneType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PhoneType>("RENTECOSAModel.FK_PersonPhone_PhoneType", "PhoneType", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RENTECOSAModel", Name="PhoneType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PhoneType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PhoneType object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static PhoneType CreatePhoneType(global::System.Int32 id, global::System.String name)
        {
            PhoneType phoneType = new PhoneType();
            phoneType.Id = id;
            phoneType.Name = name;
            return phoneType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RENTECOSAModel", "FK_PersonPhone_PhoneType", "PersonPhone")]
        public EntityCollection<PersonPhone> PersonPhones
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PersonPhone>("RENTECOSAModel.FK_PersonPhone_PhoneType", "PersonPhone");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PersonPhone>("RENTECOSAModel.FK_PersonPhone_PhoneType", "PersonPhone", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
