//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace ReplicantRepository.DataTransferObjects.NervObjects
{
    
    [DataContract(Name = "KeyAccessDto", Namespace = "http://core.renteco.com/dto/" , IsReference = true) ]
    public partial class KeyAccessDto
    {
         #region Primitive Properties
    
    	[DataMember]
        public virtual int Id
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual int UserGroupId
        {
     
    
            get { return _userGroupId; }
            set
            {
                if (_userGroupId != value)
                {
                    if (UserGroup != null && UserGroup.Id != value)
                    {
                        UserGroup = null;
                    }
                    _userGroupId = value;
                }
            }
        }
        private int _userGroupId;
    
    	[DataMember]
        public virtual int Value
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual int LatchId
        {
     
    
            get { return _latchId; }
            set
            {
                if (_latchId != value)
                {
                    if (Latch != null && Latch.Id != value)
                    {
                        Latch = null;
                    }
                    _latchId = value;
                }
            }
        }
        private int _latchId;

        #endregion
        #region Navigation Properties
    
    	[DataMember]
        public virtual LatchDto Latch
        {
            get { return _latch; }
            set
            {
                if (!ReferenceEquals(_latch, value))
                {
                    var previousValue = _latch;
                    _latch = value;
                    FixupLatch(previousValue);
                }
            }
        }
        private LatchDto _latch;
    
    	[DataMember]
        public virtual UserGroupDto UserGroup
        {
            get { return _userGroup; }
            set
            {
                if (!ReferenceEquals(_userGroup, value))
                {
                    var previousValue = _userGroup;
                    _userGroup = value;
                    FixupUserGroup(previousValue);
                }
            }
        }
        private UserGroupDto _userGroup;

        #endregion
        #region Association Fixup
    
        private void FixupLatch(LatchDto previousValue)
        {
            if (previousValue != null && previousValue.KeyAccesses.Contains(this))
            {
                previousValue.KeyAccesses.Remove(this);
            }
    
            if (Latch != null)
            {
                if (!Latch.KeyAccesses.Contains(this))
                {
                    Latch.KeyAccesses.Add(this);
                }
                if (LatchId != Latch.Id)
                {
                    LatchId = Latch.Id;
                }
            }
        }
    
        private void FixupUserGroup(UserGroupDto previousValue)
        {
            if (previousValue != null && previousValue.KeyAccesses.Contains(this))
            {
                previousValue.KeyAccesses.Remove(this);
            }
    
            if (UserGroup != null)
            {
                if (!UserGroup.KeyAccesses.Contains(this))
                {
                    UserGroup.KeyAccesses.Add(this);
                }
                if (UserGroupId != UserGroup.Id)
                {
                    UserGroupId = UserGroup.Id;
                }
            }
        }

        #endregion
    }
}
