//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace ReplicantRepository.DataTransferObjects.NervObjects
{
    
    [DataContract(Name = "UserGroupDto", Namespace = "http://core.renteco.com/dto/" , IsReference = true) ]
    public partial class UserGroupDto
    {
         #region Primitive Properties
    
    	[DataMember]
        public virtual int Id
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual string Name
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual string Description
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
    	[DataMember]
        public virtual ICollection<KeyAccessDto> KeyAccesses
        {
            get
            {
                if (_keyAccesses == null)
                {
                    var newCollection = new FixupCollection<KeyAccessDto>();
                    newCollection.CollectionChanged += FixupKeyAccesses;
                    _keyAccesses = newCollection;
                }
                return _keyAccesses;
            }
            set
            {
                if (!ReferenceEquals(_keyAccesses, value))
                {
                    var previousValue = _keyAccesses as FixupCollection<KeyAccessDto>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupKeyAccesses;
                    }
                    _keyAccesses = value;
                    var newValue = value as FixupCollection<KeyAccessDto>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupKeyAccesses;
                    }
                }
            }
        }
        private ICollection<KeyAccessDto> _keyAccesses;
    
    	[DataMember]
        public virtual ICollection<UserAccountDto> UserAccounts
        {
            get
            {
                if (_userAccounts == null)
                {
                    var newCollection = new FixupCollection<UserAccountDto>();
                    newCollection.CollectionChanged += FixupUserAccounts;
                    _userAccounts = newCollection;
                }
                return _userAccounts;
            }
            set
            {
                if (!ReferenceEquals(_userAccounts, value))
                {
                    var previousValue = _userAccounts as FixupCollection<UserAccountDto>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupUserAccounts;
                    }
                    _userAccounts = value;
                    var newValue = value as FixupCollection<UserAccountDto>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupUserAccounts;
                    }
                }
            }
        }
        private ICollection<UserAccountDto> _userAccounts;

        #endregion
        #region Association Fixup
    
        private void FixupKeyAccesses(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (KeyAccessDto item in e.NewItems)
                {
                    item.UserGroup = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (KeyAccessDto item in e.OldItems)
                {
                    if (ReferenceEquals(item.UserGroup, this))
                    {
                        item.UserGroup = null;
                    }
                }
            }
        }
    
        private void FixupUserAccounts(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (UserAccountDto item in e.NewItems)
                {
                    item.UserGroup = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (UserAccountDto item in e.OldItems)
                {
                    if (ReferenceEquals(item.UserGroup, this))
                    {
                        item.UserGroup = null;
                    }
                }
            }
        }

        #endregion
    }
}
