//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace ReplicantRepository.DataTransferObjects
{
    
    [DataContract(Name = "BindCustomerDto", Namespace = "http://core.renteco.com/dto/" , IsReference = true) ]
    public partial class BindCustomerDto
    {
         #region Primitive Properties
    
    	[DataMember]
        public virtual int CustomerId
        {
     
    
            get { return _customerId; }
            set
            {
                if (_customerId != value)
                {
                    if (Customer != null && Customer.Id != value)
                    {
                        Customer = null;
                    }
                    _customerId = value;
                }
            }
        }
        private int _customerId;
    
    	[DataMember]
        public virtual string AlienId
        {
            get;
            set;
        }
    	// Custom ToString() Method using reflection
    	// Autor: Jaime Torner
    	public override string ToString() 
    	{		
    		return CustomToStringMethods.ToString(this);
    	}
    

        #endregion
        #region Navigation Properties
    
    	[DataMember]
        public virtual CustomerDto Customer
        {
            get { return _customer; }
            set
            {
                if (!ReferenceEquals(_customer, value))
                {
                    var previousValue = _customer;
                    _customer = value;
                    FixupCustomer(previousValue);
                }
            }
        }
        private CustomerDto _customer;

        #endregion
        #region Association Fixup
    
        private void FixupCustomer(CustomerDto previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.BindCustomer, this))
            {
                previousValue.BindCustomer = null;
            }
    
            if (Customer != null)
            {
                Customer.BindCustomer = this;
                if (CustomerId != Customer.Id)
                {
                    CustomerId = Customer.Id;
                }
            }
        }

        #endregion
    }
}
