//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace ReplicantRepository.DataTransferObjects
{
    
    [DataContract(Name = "BudgetRequestConditionDto", Namespace = "http://core.renteco.com/dto/" , IsReference = true) ]
    public partial class BudgetRequestConditionDto
    {
         #region Primitive Properties
    
    	[DataMember]
        public virtual int BudgetRequestId
        {
     
    
            get { return _budgetRequestId; }
            set
            {
                if (_budgetRequestId != value)
                {
                    if (BudgetRequest != null && BudgetRequest.Id != value)
                    {
                        BudgetRequest = null;
                    }
                    _budgetRequestId = value;
                }
            }
        }
        private int _budgetRequestId;
    
    	[DataMember]
        public virtual System.DateTime StartDate
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual decimal Period
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual decimal Warranty
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual decimal SafetyCourse
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual decimal MaximunHeight
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual string Observations
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual bool Monday
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual bool Tuesday
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual bool Wednesday
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual bool Thursday
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual bool Friday
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual bool Saturday
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual bool Sunday
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual bool DayTurn
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual bool NightTurn
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual bool DrinkableWater
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual bool Electricity
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual bool Warehouse
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual bool WorkInside
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual bool WorkOutside
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual bool Reachable
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual bool Ventilation
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual bool Toilet
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual bool Moisture
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual bool Wet
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual bool Noise
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual bool Dust
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual bool Lodging
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual bool Food
        {
            get;
            set;
        }
    	// Custom ToString() Method using reflection
    	// Autor: Jaime Torner
    	public override string ToString() 
    	{		
    		return CustomToStringMethods.ToString(this);
    	}
    

        #endregion
        #region Navigation Properties
    
    	[DataMember]
        public virtual BudgetRequestDto BudgetRequest
        {
            get { return _budgetRequest; }
            set
            {
                if (!ReferenceEquals(_budgetRequest, value))
                {
                    var previousValue = _budgetRequest;
                    _budgetRequest = value;
                    FixupBudgetRequest(previousValue);
                }
            }
        }
        private BudgetRequestDto _budgetRequest;

        #endregion
        #region Association Fixup
    
        private void FixupBudgetRequest(BudgetRequestDto previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.BudgetRequestCondition, this))
            {
                previousValue.BudgetRequestCondition = null;
            }
    
            if (BudgetRequest != null)
            {
                BudgetRequest.BudgetRequestCondition = this;
                if (BudgetRequestId != BudgetRequest.Id)
                {
                    BudgetRequestId = BudgetRequest.Id;
                }
            }
        }

        #endregion
    }
}
