//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace ReplicantRepository.DataTransferObjects
{
    
    [DataContract(Name = "BudgetRequestDto", Namespace = "http://core.renteco.com/dto/" , IsReference = true) ]
    public partial class BudgetRequestDto
    {
         #region Primitive Properties
    
    	[DataMember]
        public virtual int Id
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual int CustomerId
        {
     
    
            get { return _customerId; }
            set
            {
                if (_customerId != value)
                {
                    if (Customer != null && Customer.Id != value)
                    {
                        Customer = null;
                    }
                    _customerId = value;
                }
            }
        }
        private int _customerId;
    
    	[DataMember]
        public virtual string ProjectName
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual System.DateTime DateCreated
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual System.DateTime DateModified
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual int EmployeeId
        {
     
    
            get { return _employeeId; }
            set
            {
                if (_employeeId != value)
                {
                    if (Employee != null && Employee.Id != value)
                    {
                        Employee = null;
                    }
                    _employeeId = value;
                }
            }
        }
        private int _employeeId;
    
    	[DataMember]
        public virtual int CustomerContactId
        {
     
    
            get { return _customerContactId; }
            set
            {
                if (_customerContactId != value)
                {
                    if (CustomerContact != null && CustomerContact.Id != value)
                    {
                        CustomerContact = null;
                    }
                    _customerContactId = value;
                }
            }
        }
        private int _customerContactId;
    
    	[DataMember]
        public virtual int PersonPhoneId
        {
     
    
            get { return _personPhoneId; }
            set
            {
                if (_personPhoneId != value)
                {
                    if (PersonPhone != null && PersonPhone.Id != value)
                    {
                        PersonPhone = null;
                    }
                    _personPhoneId = value;
                }
            }
        }
        private int _personPhoneId;
    
    	[DataMember]
        public virtual int FamilyId
        {
     
    
            get { return _familyId; }
            set
            {
                if (_familyId != value)
                {
                    if (Family != null && Family.Id != value)
                    {
                        Family = null;
                    }
                    _familyId = value;
                }
            }
        }
        private int _familyId;
    	// Custom ToString() Method using reflection
    	// Autor: Jaime Torner
    	public override string ToString() 
    	{		
    		return CustomToStringMethods.ToString(this);
    	}
    

        #endregion
        #region Navigation Properties
    
    	[DataMember]
        public virtual CustomerDto Customer
        {
            get { return _customer; }
            set
            {
                if (!ReferenceEquals(_customer, value))
                {
                    var previousValue = _customer;
                    _customer = value;
                    FixupCustomer(previousValue);
                }
            }
        }
        private CustomerDto _customer;
    
    	[DataMember]
        public virtual CustomerContactDto CustomerContact
        {
            get { return _customerContact; }
            set
            {
                if (!ReferenceEquals(_customerContact, value))
                {
                    var previousValue = _customerContact;
                    _customerContact = value;
                    FixupCustomerContact(previousValue);
                }
            }
        }
        private CustomerContactDto _customerContact;
    
    	[DataMember]
        public virtual EmployeeDto Employee
        {
            get { return _employee; }
            set
            {
                if (!ReferenceEquals(_employee, value))
                {
                    var previousValue = _employee;
                    _employee = value;
                    FixupEmployee(previousValue);
                }
            }
        }
        private EmployeeDto _employee;
    
    	[DataMember]
        public virtual FamilyDto Family
        {
            get { return _family; }
            set
            {
                if (!ReferenceEquals(_family, value))
                {
                    var previousValue = _family;
                    _family = value;
                    FixupFamily(previousValue);
                }
            }
        }
        private FamilyDto _family;
    
    	[DataMember]
        public virtual PersonPhoneDto PersonPhone
        {
            get { return _personPhone; }
            set
            {
                if (!ReferenceEquals(_personPhone, value))
                {
                    var previousValue = _personPhone;
                    _personPhone = value;
                    FixupPersonPhone(previousValue);
                }
            }
        }
        private PersonPhoneDto _personPhone;
    
    	[DataMember]
        public virtual BudgetRequestConditionDto BudgetRequestCondition
        {
            get { return _budgetRequestCondition; }
            set
            {
                if (!ReferenceEquals(_budgetRequestCondition, value))
                {
                    var previousValue = _budgetRequestCondition;
                    _budgetRequestCondition = value;
                    FixupBudgetRequestCondition(previousValue);
                }
            }
        }
        private BudgetRequestConditionDto _budgetRequestCondition;
    
    	[DataMember]
        public virtual ICollection<BudgetRequestDetailDto> BudgetRequestDetails
        {
            get
            {
                if (_budgetRequestDetails == null)
                {
                    var newCollection = new FixupCollection<BudgetRequestDetailDto>();
                    newCollection.CollectionChanged += FixupBudgetRequestDetails;
                    _budgetRequestDetails = newCollection;
                }
                return _budgetRequestDetails;
            }
            set
            {
                if (!ReferenceEquals(_budgetRequestDetails, value))
                {
                    var previousValue = _budgetRequestDetails as FixupCollection<BudgetRequestDetailDto>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupBudgetRequestDetails;
                    }
                    _budgetRequestDetails = value;
                    var newValue = value as FixupCollection<BudgetRequestDetailDto>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupBudgetRequestDetails;
                    }
                }
            }
        }
        private ICollection<BudgetRequestDetailDto> _budgetRequestDetails;
    
    	[DataMember]
        public virtual ICollection<ProjectDto> Projects
        {
            get
            {
                if (_projects == null)
                {
                    var newCollection = new FixupCollection<ProjectDto>();
                    newCollection.CollectionChanged += FixupProjects;
                    _projects = newCollection;
                }
                return _projects;
            }
            set
            {
                if (!ReferenceEquals(_projects, value))
                {
                    var previousValue = _projects as FixupCollection<ProjectDto>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupProjects;
                    }
                    _projects = value;
                    var newValue = value as FixupCollection<ProjectDto>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupProjects;
                    }
                }
            }
        }
        private ICollection<ProjectDto> _projects;

        #endregion
        #region Association Fixup
    
        private void FixupCustomer(CustomerDto previousValue)
        {
            if (previousValue != null && previousValue.BudgetRequests.Contains(this))
            {
                previousValue.BudgetRequests.Remove(this);
            }
    
            if (Customer != null)
            {
                if (!Customer.BudgetRequests.Contains(this))
                {
                    Customer.BudgetRequests.Add(this);
                }
                if (CustomerId != Customer.Id)
                {
                    CustomerId = Customer.Id;
                }
            }
        }
    
        private void FixupCustomerContact(CustomerContactDto previousValue)
        {
            if (previousValue != null && previousValue.BudgetRequests.Contains(this))
            {
                previousValue.BudgetRequests.Remove(this);
            }
    
            if (CustomerContact != null)
            {
                if (!CustomerContact.BudgetRequests.Contains(this))
                {
                    CustomerContact.BudgetRequests.Add(this);
                }
                if (CustomerContactId != CustomerContact.Id)
                {
                    CustomerContactId = CustomerContact.Id;
                }
            }
        }
    
        private void FixupEmployee(EmployeeDto previousValue)
        {
            if (previousValue != null && previousValue.BudgetRequests.Contains(this))
            {
                previousValue.BudgetRequests.Remove(this);
            }
    
            if (Employee != null)
            {
                if (!Employee.BudgetRequests.Contains(this))
                {
                    Employee.BudgetRequests.Add(this);
                }
                if (EmployeeId != Employee.Id)
                {
                    EmployeeId = Employee.Id;
                }
            }
        }
    
        private void FixupFamily(FamilyDto previousValue)
        {
            if (previousValue != null && previousValue.BudgetRequests.Contains(this))
            {
                previousValue.BudgetRequests.Remove(this);
            }
    
            if (Family != null)
            {
                if (!Family.BudgetRequests.Contains(this))
                {
                    Family.BudgetRequests.Add(this);
                }
                if (FamilyId != Family.Id)
                {
                    FamilyId = Family.Id;
                }
            }
        }
    
        private void FixupPersonPhone(PersonPhoneDto previousValue)
        {
            if (previousValue != null && previousValue.BudgetRequests.Contains(this))
            {
                previousValue.BudgetRequests.Remove(this);
            }
    
            if (PersonPhone != null)
            {
                if (!PersonPhone.BudgetRequests.Contains(this))
                {
                    PersonPhone.BudgetRequests.Add(this);
                }
                if (PersonPhoneId != PersonPhone.Id)
                {
                    PersonPhoneId = PersonPhone.Id;
                }
            }
        }
    
        private void FixupBudgetRequestCondition(BudgetRequestConditionDto previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.BudgetRequest, this))
            {
                previousValue.BudgetRequest = null;
            }
    
            if (BudgetRequestCondition != null)
            {
                BudgetRequestCondition.BudgetRequest = this;
            }
        }
    
        private void FixupBudgetRequestDetails(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (BudgetRequestDetailDto item in e.NewItems)
                {
                    item.BudgetRequest = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (BudgetRequestDetailDto item in e.OldItems)
                {
                    if (ReferenceEquals(item.BudgetRequest, this))
                    {
                        item.BudgetRequest = null;
                    }
                }
            }
        }
    
        private void FixupProjects(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ProjectDto item in e.NewItems)
                {
                    item.BudgetRequest = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ProjectDto item in e.OldItems)
                {
                    if (ReferenceEquals(item.BudgetRequest, this))
                    {
                        item.BudgetRequest = null;
                    }
                }
            }
        }

        #endregion
    }
}
