//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace ReplicantRepository.DataTransferObjects
{
    
    [DataContract(Name = "CustomerDto", Namespace = "http://core.renteco.com/dto/" , IsReference = true) ]
    public partial class CustomerDto
    {
         #region Primitive Properties
    
    	[DataMember]
        public virtual int Id
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual string Name
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual string Address
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual string AddressOptional
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual string Phone
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual string Fax
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
    	[DataMember]
        public virtual BindCustomerDto BindCustomer
        {
            get { return _bindCustomer; }
            set
            {
                if (!ReferenceEquals(_bindCustomer, value))
                {
                    var previousValue = _bindCustomer;
                    _bindCustomer = value;
                    FixupBindCustomer(previousValue);
                }
            }
        }
        private BindCustomerDto _bindCustomer;
    
    	[DataMember]
        public virtual ICollection<BudgetRequestDto> BudgetRequests
        {
            get
            {
                if (_budgetRequests == null)
                {
                    var newCollection = new FixupCollection<BudgetRequestDto>();
                    newCollection.CollectionChanged += FixupBudgetRequests;
                    _budgetRequests = newCollection;
                }
                return _budgetRequests;
            }
            set
            {
                if (!ReferenceEquals(_budgetRequests, value))
                {
                    var previousValue = _budgetRequests as FixupCollection<BudgetRequestDto>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupBudgetRequests;
                    }
                    _budgetRequests = value;
                    var newValue = value as FixupCollection<BudgetRequestDto>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupBudgetRequests;
                    }
                }
            }
        }
        private ICollection<BudgetRequestDto> _budgetRequests;
    
    	[DataMember]
        public virtual ICollection<CustomerContactDto> CustomerContacts
        {
            get
            {
                if (_customerContacts == null)
                {
                    var newCollection = new FixupCollection<CustomerContactDto>();
                    newCollection.CollectionChanged += FixupCustomerContacts;
                    _customerContacts = newCollection;
                }
                return _customerContacts;
            }
            set
            {
                if (!ReferenceEquals(_customerContacts, value))
                {
                    var previousValue = _customerContacts as FixupCollection<CustomerContactDto>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCustomerContacts;
                    }
                    _customerContacts = value;
                    var newValue = value as FixupCollection<CustomerContactDto>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCustomerContacts;
                    }
                }
            }
        }
        private ICollection<CustomerContactDto> _customerContacts;
    
    	[DataMember]
        public virtual ICollection<ProjectDto> Projects
        {
            get
            {
                if (_projects == null)
                {
                    var newCollection = new FixupCollection<ProjectDto>();
                    newCollection.CollectionChanged += FixupProjects;
                    _projects = newCollection;
                }
                return _projects;
            }
            set
            {
                if (!ReferenceEquals(_projects, value))
                {
                    var previousValue = _projects as FixupCollection<ProjectDto>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupProjects;
                    }
                    _projects = value;
                    var newValue = value as FixupCollection<ProjectDto>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupProjects;
                    }
                }
            }
        }
        private ICollection<ProjectDto> _projects;
    
    	[DataMember]
        public virtual ICollection<EmployeeDto> Employees
        {
            get
            {
                if (_employees == null)
                {
                    var newCollection = new FixupCollection<EmployeeDto>();
                    newCollection.CollectionChanged += FixupEmployees;
                    _employees = newCollection;
                }
                return _employees;
            }
            set
            {
                if (!ReferenceEquals(_employees, value))
                {
                    var previousValue = _employees as FixupCollection<EmployeeDto>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupEmployees;
                    }
                    _employees = value;
                    var newValue = value as FixupCollection<EmployeeDto>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupEmployees;
                    }
                }
            }
        }
        private ICollection<EmployeeDto> _employees;

        #endregion
        #region Association Fixup
    
        private void FixupBindCustomer(BindCustomerDto previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.Customer, this))
            {
                previousValue.Customer = null;
            }
    
            if (BindCustomer != null)
            {
                BindCustomer.Customer = this;
            }
        }
    
        private void FixupBudgetRequests(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (BudgetRequestDto item in e.NewItems)
                {
                    item.Customer = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (BudgetRequestDto item in e.OldItems)
                {
                    if (ReferenceEquals(item.Customer, this))
                    {
                        item.Customer = null;
                    }
                }
            }
        }
    
        private void FixupCustomerContacts(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (CustomerContactDto item in e.NewItems)
                {
                    item.Customer = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (CustomerContactDto item in e.OldItems)
                {
                    if (ReferenceEquals(item.Customer, this))
                    {
                        item.Customer = null;
                    }
                }
            }
        }
    
        private void FixupProjects(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ProjectDto item in e.NewItems)
                {
                    item.Customer = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ProjectDto item in e.OldItems)
                {
                    if (ReferenceEquals(item.Customer, this))
                    {
                        item.Customer = null;
                    }
                }
            }
        }
    
        private void FixupEmployees(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (EmployeeDto item in e.NewItems)
                {
                    if (!item.Customers.Contains(this))
                    {
                        item.Customers.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (EmployeeDto item in e.OldItems)
                {
                    if (item.Customers.Contains(this))
                    {
                        item.Customers.Remove(this);
                    }
                }
            }
        }

        #endregion
    }
}
