//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace ReplicantRepository.DataTransferObjects
{
    
    [DataContract(Name = "ItemDto", Namespace = "http://core.renteco.com/dto/" , IsReference = true) ]
    public partial class ItemDto
    {
         #region Primitive Properties
    
    	[DataMember]
        public virtual int Id
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual string Name
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual string Code
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual decimal Cost
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual decimal Price
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual bool IsTaxed
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual System.DateTime DateCreated
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual System.DateTime DateModified
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual int MaximunDiscount
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual bool WasDeleted
        {
            get;
            set;
        }
    	// Custom ToString() Method using reflection
    	// Autor: Jaime Torner
    	public override string ToString() 
    	{		
    		return CustomToStringMethods.ToString(this);
    	}
    

        #endregion
        #region Navigation Properties
    
    	[DataMember]
        public virtual ICollection<BudgetRequestDetailDto> BudgetRequestDetails
        {
            get
            {
                if (_budgetRequestDetails == null)
                {
                    var newCollection = new FixupCollection<BudgetRequestDetailDto>();
                    newCollection.CollectionChanged += FixupBudgetRequestDetails;
                    _budgetRequestDetails = newCollection;
                }
                return _budgetRequestDetails;
            }
            set
            {
                if (!ReferenceEquals(_budgetRequestDetails, value))
                {
                    var previousValue = _budgetRequestDetails as FixupCollection<BudgetRequestDetailDto>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupBudgetRequestDetails;
                    }
                    _budgetRequestDetails = value;
                    var newValue = value as FixupCollection<BudgetRequestDetailDto>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupBudgetRequestDetails;
                    }
                }
            }
        }
        private ICollection<BudgetRequestDetailDto> _budgetRequestDetails;
    
    	[DataMember]
        public virtual ICollection<StockDto> Stocks
        {
            get
            {
                if (_stocks == null)
                {
                    var newCollection = new FixupCollection<StockDto>();
                    newCollection.CollectionChanged += FixupStocks;
                    _stocks = newCollection;
                }
                return _stocks;
            }
            set
            {
                if (!ReferenceEquals(_stocks, value))
                {
                    var previousValue = _stocks as FixupCollection<StockDto>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupStocks;
                    }
                    _stocks = value;
                    var newValue = value as FixupCollection<StockDto>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupStocks;
                    }
                }
            }
        }
        private ICollection<StockDto> _stocks;

        #endregion
        #region Association Fixup
    
        private void FixupBudgetRequestDetails(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (BudgetRequestDetailDto item in e.NewItems)
                {
                    item.Item = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (BudgetRequestDetailDto item in e.OldItems)
                {
                    if (ReferenceEquals(item.Item, this))
                    {
                        item.Item = null;
                    }
                }
            }
        }
    
        private void FixupStocks(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (StockDto item in e.NewItems)
                {
                    item.Item = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (StockDto item in e.OldItems)
                {
                    if (ReferenceEquals(item.Item, this))
                    {
                        item.Item = null;
                    }
                }
            }
        }

        #endregion
    }
}
