//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace ReplicantRepository.DataTransferObjects
{
    
    [DataContract(Name = "MeasureDto", Namespace = "http://core.renteco.com/dto/" , IsReference = true) ]
    public partial class MeasureDto
    {
         #region Primitive Properties
    
    	[DataMember]
        public virtual int Id
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual string Name
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual string Symbol
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
    	[DataMember]
        public virtual ICollection<BudgetRequestDetailDto> BudgetRequestDetails
        {
            get
            {
                if (_budgetRequestDetails == null)
                {
                    var newCollection = new FixupCollection<BudgetRequestDetailDto>();
                    newCollection.CollectionChanged += FixupBudgetRequestDetails;
                    _budgetRequestDetails = newCollection;
                }
                return _budgetRequestDetails;
            }
            set
            {
                if (!ReferenceEquals(_budgetRequestDetails, value))
                {
                    var previousValue = _budgetRequestDetails as FixupCollection<BudgetRequestDetailDto>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupBudgetRequestDetails;
                    }
                    _budgetRequestDetails = value;
                    var newValue = value as FixupCollection<BudgetRequestDetailDto>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupBudgetRequestDetails;
                    }
                }
            }
        }
        private ICollection<BudgetRequestDetailDto> _budgetRequestDetails;
    
    	[DataMember]
        public virtual ICollection<ResourceDto> Resources
        {
            get
            {
                if (_resources == null)
                {
                    var newCollection = new FixupCollection<ResourceDto>();
                    newCollection.CollectionChanged += FixupResources;
                    _resources = newCollection;
                }
                return _resources;
            }
            set
            {
                if (!ReferenceEquals(_resources, value))
                {
                    var previousValue = _resources as FixupCollection<ResourceDto>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupResources;
                    }
                    _resources = value;
                    var newValue = value as FixupCollection<ResourceDto>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupResources;
                    }
                }
            }
        }
        private ICollection<ResourceDto> _resources;

        #endregion
        #region Association Fixup
    
        private void FixupBudgetRequestDetails(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (BudgetRequestDetailDto item in e.NewItems)
                {
                    item.Measure = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (BudgetRequestDetailDto item in e.OldItems)
                {
                    if (ReferenceEquals(item.Measure, this))
                    {
                        item.Measure = null;
                    }
                }
            }
        }
    
        private void FixupResources(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ResourceDto item in e.NewItems)
                {
                    item.Measure = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ResourceDto item in e.OldItems)
                {
                    if (ReferenceEquals(item.Measure, this))
                    {
                        item.Measure = null;
                    }
                }
            }
        }

        #endregion
    }
}
