//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace ReplicantRepository.DataTransferObjects
{
    
    [DataContract(Name = "PersonDto", Namespace = "http://core.renteco.com/dto/" , IsReference = true) ]
    public partial class PersonDto
    {
         #region Primitive Properties
    
    	[DataMember]
        public virtual int Id
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual string Name
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual string LastName
        {
            get;
            set;
        }
    	// Custom ToString() Method using reflection
    	// Autor: Jaime Torner
    	public override string ToString() 
    	{		
    		return CustomToStringMethods.ToString(this);
    	}
    

        #endregion
        #region Navigation Properties
    
    	[DataMember]
        public virtual ICollection<CustomerContactDto> CustomerContacts
        {
            get
            {
                if (_customerContacts == null)
                {
                    var newCollection = new FixupCollection<CustomerContactDto>();
                    newCollection.CollectionChanged += FixupCustomerContacts;
                    _customerContacts = newCollection;
                }
                return _customerContacts;
            }
            set
            {
                if (!ReferenceEquals(_customerContacts, value))
                {
                    var previousValue = _customerContacts as FixupCollection<CustomerContactDto>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCustomerContacts;
                    }
                    _customerContacts = value;
                    var newValue = value as FixupCollection<CustomerContactDto>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCustomerContacts;
                    }
                }
            }
        }
        private ICollection<CustomerContactDto> _customerContacts;
    
    	[DataMember]
        public virtual ICollection<EmployeeDto> Employees
        {
            get
            {
                if (_employees == null)
                {
                    var newCollection = new FixupCollection<EmployeeDto>();
                    newCollection.CollectionChanged += FixupEmployees;
                    _employees = newCollection;
                }
                return _employees;
            }
            set
            {
                if (!ReferenceEquals(_employees, value))
                {
                    var previousValue = _employees as FixupCollection<EmployeeDto>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupEmployees;
                    }
                    _employees = value;
                    var newValue = value as FixupCollection<EmployeeDto>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupEmployees;
                    }
                }
            }
        }
        private ICollection<EmployeeDto> _employees;
    
    	[DataMember]
        public virtual ICollection<PersonPhoneDto> PersonPhones
        {
            get
            {
                if (_personPhones == null)
                {
                    var newCollection = new FixupCollection<PersonPhoneDto>();
                    newCollection.CollectionChanged += FixupPersonPhones;
                    _personPhones = newCollection;
                }
                return _personPhones;
            }
            set
            {
                if (!ReferenceEquals(_personPhones, value))
                {
                    var previousValue = _personPhones as FixupCollection<PersonPhoneDto>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupPersonPhones;
                    }
                    _personPhones = value;
                    var newValue = value as FixupCollection<PersonPhoneDto>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupPersonPhones;
                    }
                }
            }
        }
        private ICollection<PersonPhoneDto> _personPhones;

        #endregion
        #region Association Fixup
    
        private void FixupCustomerContacts(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (CustomerContactDto item in e.NewItems)
                {
                    item.Person = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (CustomerContactDto item in e.OldItems)
                {
                    if (ReferenceEquals(item.Person, this))
                    {
                        item.Person = null;
                    }
                }
            }
        }
    
        private void FixupEmployees(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (EmployeeDto item in e.NewItems)
                {
                    item.Person = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (EmployeeDto item in e.OldItems)
                {
                    if (ReferenceEquals(item.Person, this))
                    {
                        item.Person = null;
                    }
                }
            }
        }
    
        private void FixupPersonPhones(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (PersonPhoneDto item in e.NewItems)
                {
                    item.Person = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (PersonPhoneDto item in e.OldItems)
                {
                    if (ReferenceEquals(item.Person, this))
                    {
                        item.Person = null;
                    }
                }
            }
        }

        #endregion
    }
}
