//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace ReplicantRepository.DataTransferObjects
{
    
    [DataContract(Name = "PersonPhoneDto", Namespace = "http://core.renteco.com/dto/" , IsReference = true) ]
    public partial class PersonPhoneDto
    {
         #region Primitive Properties
    
    	[DataMember]
        public virtual int Id
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual string Phone
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual int PhoneTypeId
        {
     
    
            get { return _phoneTypeId; }
            set
            {
                if (_phoneTypeId != value)
                {
                    if (PhoneType != null && PhoneType.Id != value)
                    {
                        PhoneType = null;
                    }
                    _phoneTypeId = value;
                }
            }
        }
        private int _phoneTypeId;
    
    	[DataMember]
        public virtual int PersonId
        {
     
    
            get { return _personId; }
            set
            {
                if (_personId != value)
                {
                    if (Person != null && Person.Id != value)
                    {
                        Person = null;
                    }
                    _personId = value;
                }
            }
        }
        private int _personId;

        #endregion
        #region Navigation Properties
    
    	[DataMember]
        public virtual PersonDto Person
        {
            get { return _person; }
            set
            {
                if (!ReferenceEquals(_person, value))
                {
                    var previousValue = _person;
                    _person = value;
                    FixupPerson(previousValue);
                }
            }
        }
        private PersonDto _person;
    
    	[DataMember]
        public virtual PhoneTypeDto PhoneType
        {
            get { return _phoneType; }
            set
            {
                if (!ReferenceEquals(_phoneType, value))
                {
                    var previousValue = _phoneType;
                    _phoneType = value;
                    FixupPhoneType(previousValue);
                }
            }
        }
        private PhoneTypeDto _phoneType;

        #endregion
        #region Association Fixup
    
        private void FixupPerson(PersonDto previousValue)
        {
            if (previousValue != null && previousValue.PersonPhones.Contains(this))
            {
                previousValue.PersonPhones.Remove(this);
            }
    
            if (Person != null)
            {
                if (!Person.PersonPhones.Contains(this))
                {
                    Person.PersonPhones.Add(this);
                }
                if (PersonId != Person.Id)
                {
                    PersonId = Person.Id;
                }
            }
        }
    
        private void FixupPhoneType(PhoneTypeDto previousValue)
        {
            if (previousValue != null && previousValue.PersonPhones.Contains(this))
            {
                previousValue.PersonPhones.Remove(this);
            }
    
            if (PhoneType != null)
            {
                if (!PhoneType.PersonPhones.Contains(this))
                {
                    PhoneType.PersonPhones.Add(this);
                }
                if (PhoneTypeId != PhoneType.Id)
                {
                    PhoneTypeId = PhoneType.Id;
                }
            }
        }

        #endregion
    }
}
