//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace ReplicantRepository.DataTransferObjects
{
    
    [DataContract(Name = "PhoneTypeDto", Namespace = "http://core.renteco.com/dto/" , IsReference = true) ]
    public partial class PhoneTypeDto
    {
         #region Primitive Properties
    
    	[DataMember]
        public virtual int Id
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual string Name
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
    	[DataMember]
        public virtual ICollection<PersonPhoneDto> PersonPhones
        {
            get
            {
                if (_personPhones == null)
                {
                    var newCollection = new FixupCollection<PersonPhoneDto>();
                    newCollection.CollectionChanged += FixupPersonPhones;
                    _personPhones = newCollection;
                }
                return _personPhones;
            }
            set
            {
                if (!ReferenceEquals(_personPhones, value))
                {
                    var previousValue = _personPhones as FixupCollection<PersonPhoneDto>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupPersonPhones;
                    }
                    _personPhones = value;
                    var newValue = value as FixupCollection<PersonPhoneDto>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupPersonPhones;
                    }
                }
            }
        }
        private ICollection<PersonPhoneDto> _personPhones;

        #endregion
        #region Association Fixup
    
        private void FixupPersonPhones(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (PersonPhoneDto item in e.NewItems)
                {
                    item.PhoneType = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (PersonPhoneDto item in e.OldItems)
                {
                    if (ReferenceEquals(item.PhoneType, this))
                    {
                        item.PhoneType = null;
                    }
                }
            }
        }

        #endregion
    }
}
