//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace ReplicantRepository.DataTransferObjects
{
    
    [DataContract(Name = "ResourceDto", Namespace = "http://core.renteco.com/dto/" , IsReference = true) ]
    public partial class ResourceDto
    {
         #region Primitive Properties
    
    	[DataMember]
        public virtual int Id
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual int ProjectId
        {
     
    
            get { return _projectId; }
            set
            {
                if (_projectId != value)
                {
                    if (Task != null && Task.ProjectId != value)
                    {
                        Task = null;
                    }
                    _projectId = value;
                }
            }
        }
        private int _projectId;
    
    	[DataMember]
        public virtual int MeasureId
        {
     
    
            get { return _measureId; }
            set
            {
                if (_measureId != value)
                {
                    if (Measure != null && Measure.Id != value)
                    {
                        Measure = null;
                    }
                    _measureId = value;
                }
            }
        }
        private int _measureId;
    
    	[DataMember]
        public virtual int ResourceTypeId
        {
     
    
            get { return _resourceTypeId; }
            set
            {
                if (_resourceTypeId != value)
                {
                    if (ResourceType != null && ResourceType.Id != value)
                    {
                        ResourceType = null;
                    }
                    _resourceTypeId = value;
                }
            }
        }
        private int _resourceTypeId;
    
    	[DataMember]
        public virtual long TaskId
        {
     
    
            get { return _taskId; }
            set
            {
                if (_taskId != value)
                {
                    if (Task != null && Task.Id != value)
                    {
                        Task = null;
                    }
                    _taskId = value;
                }
            }
        }
        private long _taskId;
    
    	[DataMember]
        public virtual int Code
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual string Name
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual double Amount
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual decimal Cost
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual decimal TotalCost
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual double RealUsed
        {
            get;
            set;
        }
    	// Custom ToString() Method using reflection
    	// Autor: Jaime Torner
    	public override string ToString() 
    	{		
    		return CustomToStringMethods.ToString(this);
    	}
    

        #endregion
        #region Navigation Properties
    
    	[DataMember]
        public virtual MeasureDto Measure
        {
            get { return _measure; }
            set
            {
                if (!ReferenceEquals(_measure, value))
                {
                    var previousValue = _measure;
                    _measure = value;
                    FixupMeasure(previousValue);
                }
            }
        }
        private MeasureDto _measure;
    
    	[DataMember]
        public virtual ResourceTypeDto ResourceType
        {
            get { return _resourceType; }
            set
            {
                if (!ReferenceEquals(_resourceType, value))
                {
                    var previousValue = _resourceType;
                    _resourceType = value;
                    FixupResourceType(previousValue);
                }
            }
        }
        private ResourceTypeDto _resourceType;
    
    	[DataMember]
        public virtual TaskDto Task
        {
            get { return _task; }
            set
            {
                if (!ReferenceEquals(_task, value))
                {
                    var previousValue = _task;
                    _task = value;
                    FixupTask(previousValue);
                }
            }
        }
        private TaskDto _task;

        #endregion
        #region Association Fixup
    
        private void FixupMeasure(MeasureDto previousValue)
        {
            if (previousValue != null && previousValue.Resources.Contains(this))
            {
                previousValue.Resources.Remove(this);
            }
    
            if (Measure != null)
            {
                if (!Measure.Resources.Contains(this))
                {
                    Measure.Resources.Add(this);
                }
                if (MeasureId != Measure.Id)
                {
                    MeasureId = Measure.Id;
                }
            }
        }
    
        private void FixupResourceType(ResourceTypeDto previousValue)
        {
            if (previousValue != null && previousValue.Resources.Contains(this))
            {
                previousValue.Resources.Remove(this);
            }
    
            if (ResourceType != null)
            {
                if (!ResourceType.Resources.Contains(this))
                {
                    ResourceType.Resources.Add(this);
                }
                if (ResourceTypeId != ResourceType.Id)
                {
                    ResourceTypeId = ResourceType.Id;
                }
            }
        }
    
        private void FixupTask(TaskDto previousValue)
        {
            if (previousValue != null && previousValue.Resources.Contains(this))
            {
                previousValue.Resources.Remove(this);
            }
    
            if (Task != null)
            {
                if (!Task.Resources.Contains(this))
                {
                    Task.Resources.Add(this);
                }
                if (TaskId != Task.Id)
                {
                    TaskId = Task.Id;
                }
                if (ProjectId != Task.ProjectId)
                {
                    ProjectId = Task.ProjectId;
                }
            }
        }

        #endregion
    }
}
