//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace ReplicantRepository.DataTransferObjects
{
    
    [DataContract(Name = "StateDto", Namespace = "http://core.renteco.com/dto/" , IsReference = true) ]
    public partial class StateDto
    {
         #region Primitive Properties
    
    	[DataMember]
        public virtual int Id
        {
            get;
            set;
        }
    
    	[DataMember]
        public virtual string Name
        {
            get;
            set;
        }
    	// Custom ToString() Method using reflection
    	// Autor: Jaime Torner
    	public override string ToString() 
    	{		
    		return CustomToStringMethods.ToString(this);
    	}
    

        #endregion
        #region Navigation Properties
    
    	[DataMember]
        public virtual ICollection<ProjectDto> Projects
        {
            get
            {
                if (_projects == null)
                {
                    var newCollection = new FixupCollection<ProjectDto>();
                    newCollection.CollectionChanged += FixupProjects;
                    _projects = newCollection;
                }
                return _projects;
            }
            set
            {
                if (!ReferenceEquals(_projects, value))
                {
                    var previousValue = _projects as FixupCollection<ProjectDto>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupProjects;
                    }
                    _projects = value;
                    var newValue = value as FixupCollection<ProjectDto>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupProjects;
                    }
                }
            }
        }
        private ICollection<ProjectDto> _projects;
    
    	[DataMember]
        public virtual ICollection<ProjectInformDto> ProjectInforms
        {
            get
            {
                if (_projectInforms == null)
                {
                    var newCollection = new FixupCollection<ProjectInformDto>();
                    newCollection.CollectionChanged += FixupProjectInforms;
                    _projectInforms = newCollection;
                }
                return _projectInforms;
            }
            set
            {
                if (!ReferenceEquals(_projectInforms, value))
                {
                    var previousValue = _projectInforms as FixupCollection<ProjectInformDto>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupProjectInforms;
                    }
                    _projectInforms = value;
                    var newValue = value as FixupCollection<ProjectInformDto>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupProjectInforms;
                    }
                }
            }
        }
        private ICollection<ProjectInformDto> _projectInforms;

        #endregion
        #region Association Fixup
    
        private void FixupProjects(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ProjectDto item in e.NewItems)
                {
                    item.State = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ProjectDto item in e.OldItems)
                {
                    if (ReferenceEquals(item.State, this))
                    {
                        item.State = null;
                    }
                }
            }
        }
    
        private void FixupProjectInforms(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ProjectInformDto item in e.NewItems)
                {
                    item.State = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ProjectInformDto item in e.OldItems)
                {
                    if (ReferenceEquals(item.State, this))
                    {
                        item.State = null;
                    }
                }
            }
        }

        #endregion
    }
}
