USE [master]
GO

/****** Object:  Database [RENTECOSA]    Script Date: 08/19/2011 18:35:00 ******/
CREATE DATABASE [RENTECOSA] ON  PRIMARY 
( NAME = N'RENTECO', FILENAME = N'D:\DATABASE\RENTECO.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'RENTECO_log', FILENAME = N'D:\DATABASE\RENTECO_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [RENTECOSA] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RENTECOSA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RENTECOSA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RENTECOSA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RENTECOSA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RENTECOSA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RENTECOSA] SET ARITHABORT OFF 
GO

ALTER DATABASE [RENTECOSA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RENTECOSA] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [RENTECOSA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RENTECOSA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RENTECOSA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RENTECOSA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RENTECOSA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RENTECOSA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RENTECOSA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RENTECOSA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RENTECOSA] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RENTECOSA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RENTECOSA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RENTECOSA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RENTECOSA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RENTECOSA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RENTECOSA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RENTECOSA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RENTECOSA] SET  READ_WRITE 
GO

ALTER DATABASE [RENTECOSA] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [RENTECOSA] SET  MULTI_USER 
GO

ALTER DATABASE [RENTECOSA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RENTECOSA] SET DB_CHAINING OFF 
GO

