//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Interceptor.DataBase
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ForeingEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ForeingEntities object using the connection string found in the 'ForeingEntities' section of the application configuration file.
        /// </summary>
        public ForeingEntities() : base("name=ForeingEntities", "ForeingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ForeingEntities object.
        /// </summary>
        public ForeingEntities(string connectionString) : base(connectionString, "ForeingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ForeingEntities object.
        /// </summary>
        public ForeingEntities(EntityConnection connection) : base(connection, "ForeingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CLI_CLIENTES> CLI_CLIENTES
        {
            get
            {
                if ((_CLI_CLIENTES == null))
                {
                    _CLI_CLIENTES = base.CreateObjectSet<CLI_CLIENTES>("CLI_CLIENTES");
                }
                return _CLI_CLIENTES;
            }
        }
        private ObjectSet<CLI_CLIENTES> _CLI_CLIENTES;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ResourceSource> ResourceSources
        {
            get
            {
                if ((_ResourceSources == null))
                {
                    _ResourceSources = base.CreateObjectSet<ResourceSource>("ResourceSources");
                }
                return _ResourceSources;
            }
        }
        private ObjectSet<ResourceSource> _ResourceSources;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CLI_CLIENTES EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCLI_CLIENTES(CLI_CLIENTES cLI_CLIENTES)
        {
            base.AddObject("CLI_CLIENTES", cLI_CLIENTES);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ResourceSources EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToResourceSources(ResourceSource resourceSource)
        {
            base.AddObject("ResourceSources", resourceSource);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OuterModel", Name="CLI_CLIENTES")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CLI_CLIENTES : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CLI_CLIENTES object.
        /// </summary>
        /// <param name="cIA_Codigo">Initial value of the CIA_Codigo property.</param>
        /// <param name="cLI_Cliente">Initial value of the CLI_Cliente property.</param>
        /// <param name="cLI_Descuento">Initial value of the CLI_Descuento property.</param>
        /// <param name="cLI_Saldo">Initial value of the CLI_Saldo property.</param>
        /// <param name="cLI_SaldoDolar">Initial value of the CLI_SaldoDolar property.</param>
        /// <param name="cLI_MaximoCredito">Initial value of the CLI_MaximoCredito property.</param>
        /// <param name="cLI_ConImpuesto">Initial value of the CLI_ConImpuesto property.</param>
        /// <param name="cLI_DiasCredito">Initial value of the CLI_DiasCredito property.</param>
        /// <param name="cLI_SaldoReporte">Initial value of the CLI_SaldoReporte property.</param>
        /// <param name="cLI_SaldoAdelantos">Initial value of the CLI_SaldoAdelantos property.</param>
        /// <param name="cLI_Activo">Initial value of the CLI_Activo property.</param>
        /// <param name="cLI_Varios">Initial value of the CLI_Varios property.</param>
        /// <param name="cLI_CredPendDolares">Initial value of the CLI_CredPendDolares property.</param>
        /// <param name="cLI_CredPendColones">Initial value of the CLI_CredPendColones property.</param>
        /// <param name="cLI_SaldoRealColones">Initial value of the CLI_SaldoRealColones property.</param>
        /// <param name="cLI_SaldoRealDolares">Initial value of the CLI_SaldoRealDolares property.</param>
        /// <param name="cli_Administrativo">Initial value of the cli_Administrativo property.</param>
        /// <param name="cli_Judicial">Initial value of the cli_Judicial property.</param>
        public static CLI_CLIENTES CreateCLI_CLIENTES(global::System.String cIA_Codigo, global::System.String cLI_Cliente, global::System.Double cLI_Descuento, global::System.Double cLI_Saldo, global::System.Double cLI_SaldoDolar, global::System.Double cLI_MaximoCredito, global::System.Int16 cLI_ConImpuesto, global::System.Int16 cLI_DiasCredito, global::System.Double cLI_SaldoReporte, global::System.Double cLI_SaldoAdelantos, global::System.Int32 cLI_Activo, global::System.Int32 cLI_Varios, global::System.Double cLI_CredPendDolares, global::System.Double cLI_CredPendColones, global::System.Double cLI_SaldoRealColones, global::System.Double cLI_SaldoRealDolares, global::System.Int32 cli_Administrativo, global::System.Int32 cli_Judicial)
        {
            CLI_CLIENTES cLI_CLIENTES = new CLI_CLIENTES();
            cLI_CLIENTES.CIA_Codigo = cIA_Codigo;
            cLI_CLIENTES.CLI_Cliente = cLI_Cliente;
            cLI_CLIENTES.CLI_Descuento = cLI_Descuento;
            cLI_CLIENTES.CLI_Saldo = cLI_Saldo;
            cLI_CLIENTES.CLI_SaldoDolar = cLI_SaldoDolar;
            cLI_CLIENTES.CLI_MaximoCredito = cLI_MaximoCredito;
            cLI_CLIENTES.CLI_ConImpuesto = cLI_ConImpuesto;
            cLI_CLIENTES.CLI_DiasCredito = cLI_DiasCredito;
            cLI_CLIENTES.CLI_SaldoReporte = cLI_SaldoReporte;
            cLI_CLIENTES.CLI_SaldoAdelantos = cLI_SaldoAdelantos;
            cLI_CLIENTES.CLI_Activo = cLI_Activo;
            cLI_CLIENTES.CLI_Varios = cLI_Varios;
            cLI_CLIENTES.CLI_CredPendDolares = cLI_CredPendDolares;
            cLI_CLIENTES.CLI_CredPendColones = cLI_CredPendColones;
            cLI_CLIENTES.CLI_SaldoRealColones = cLI_SaldoRealColones;
            cLI_CLIENTES.CLI_SaldoRealDolares = cLI_SaldoRealDolares;
            cLI_CLIENTES.cli_Administrativo = cli_Administrativo;
            cLI_CLIENTES.cli_Judicial = cli_Judicial;
            return cLI_CLIENTES;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CIA_Codigo
        {
            get
            {
                return _CIA_Codigo;
            }
            set
            {
                if (_CIA_Codigo != value)
                {
                    OnCIA_CodigoChanging(value);
                    ReportPropertyChanging("CIA_Codigo");
                    _CIA_Codigo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CIA_Codigo");
                    OnCIA_CodigoChanged();
                }
            }
        }
        private global::System.String _CIA_Codigo;
        partial void OnCIA_CodigoChanging(global::System.String value);
        partial void OnCIA_CodigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CLI_Cliente
        {
            get
            {
                return _CLI_Cliente;
            }
            set
            {
                if (_CLI_Cliente != value)
                {
                    OnCLI_ClienteChanging(value);
                    ReportPropertyChanging("CLI_Cliente");
                    _CLI_Cliente = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CLI_Cliente");
                    OnCLI_ClienteChanged();
                }
            }
        }
        private global::System.String _CLI_Cliente;
        partial void OnCLI_ClienteChanging(global::System.String value);
        partial void OnCLI_ClienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CLI_Nombre
        {
            get
            {
                return _CLI_Nombre;
            }
            set
            {
                OnCLI_NombreChanging(value);
                ReportPropertyChanging("CLI_Nombre");
                _CLI_Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CLI_Nombre");
                OnCLI_NombreChanged();
            }
        }
        private global::System.String _CLI_Nombre;
        partial void OnCLI_NombreChanging(global::System.String value);
        partial void OnCLI_NombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CLI_CedulaJuridica
        {
            get
            {
                return _CLI_CedulaJuridica;
            }
            set
            {
                OnCLI_CedulaJuridicaChanging(value);
                ReportPropertyChanging("CLI_CedulaJuridica");
                _CLI_CedulaJuridica = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CLI_CedulaJuridica");
                OnCLI_CedulaJuridicaChanged();
            }
        }
        private global::System.String _CLI_CedulaJuridica;
        partial void OnCLI_CedulaJuridicaChanging(global::System.String value);
        partial void OnCLI_CedulaJuridicaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CLI_Telefono
        {
            get
            {
                return _CLI_Telefono;
            }
            set
            {
                OnCLI_TelefonoChanging(value);
                ReportPropertyChanging("CLI_Telefono");
                _CLI_Telefono = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CLI_Telefono");
                OnCLI_TelefonoChanged();
            }
        }
        private global::System.String _CLI_Telefono;
        partial void OnCLI_TelefonoChanging(global::System.String value);
        partial void OnCLI_TelefonoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CLI_Fax
        {
            get
            {
                return _CLI_Fax;
            }
            set
            {
                OnCLI_FaxChanging(value);
                ReportPropertyChanging("CLI_Fax");
                _CLI_Fax = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CLI_Fax");
                OnCLI_FaxChanged();
            }
        }
        private global::System.String _CLI_Fax;
        partial void OnCLI_FaxChanging(global::System.String value);
        partial void OnCLI_FaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CLI_Direccion
        {
            get
            {
                return _CLI_Direccion;
            }
            set
            {
                OnCLI_DireccionChanging(value);
                ReportPropertyChanging("CLI_Direccion");
                _CLI_Direccion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CLI_Direccion");
                OnCLI_DireccionChanged();
            }
        }
        private global::System.String _CLI_Direccion;
        partial void OnCLI_DireccionChanging(global::System.String value);
        partial void OnCLI_DireccionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CLI_Contacto
        {
            get
            {
                return _CLI_Contacto;
            }
            set
            {
                OnCLI_ContactoChanging(value);
                ReportPropertyChanging("CLI_Contacto");
                _CLI_Contacto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CLI_Contacto");
                OnCLI_ContactoChanged();
            }
        }
        private global::System.String _CLI_Contacto;
        partial void OnCLI_ContactoChanging(global::System.String value);
        partial void OnCLI_ContactoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CLI_Apartado
        {
            get
            {
                return _CLI_Apartado;
            }
            set
            {
                OnCLI_ApartadoChanging(value);
                ReportPropertyChanging("CLI_Apartado");
                _CLI_Apartado = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CLI_Apartado");
                OnCLI_ApartadoChanged();
            }
        }
        private global::System.String _CLI_Apartado;
        partial void OnCLI_ApartadoChanging(global::System.String value);
        partial void OnCLI_ApartadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CLI_Mail
        {
            get
            {
                return _CLI_Mail;
            }
            set
            {
                OnCLI_MailChanging(value);
                ReportPropertyChanging("CLI_Mail");
                _CLI_Mail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CLI_Mail");
                OnCLI_MailChanged();
            }
        }
        private global::System.String _CLI_Mail;
        partial void OnCLI_MailChanging(global::System.String value);
        partial void OnCLI_MailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double CLI_Descuento
        {
            get
            {
                return _CLI_Descuento;
            }
            set
            {
                OnCLI_DescuentoChanging(value);
                ReportPropertyChanging("CLI_Descuento");
                _CLI_Descuento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CLI_Descuento");
                OnCLI_DescuentoChanged();
            }
        }
        private global::System.Double _CLI_Descuento;
        partial void OnCLI_DescuentoChanging(global::System.Double value);
        partial void OnCLI_DescuentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VEN_Vendedor
        {
            get
            {
                return _VEN_Vendedor;
            }
            set
            {
                OnVEN_VendedorChanging(value);
                ReportPropertyChanging("VEN_Vendedor");
                _VEN_Vendedor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VEN_Vendedor");
                OnVEN_VendedorChanged();
            }
        }
        private global::System.String _VEN_Vendedor;
        partial void OnVEN_VendedorChanging(global::System.String value);
        partial void OnVEN_VendedorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZON_Codigo
        {
            get
            {
                return _ZON_Codigo;
            }
            set
            {
                OnZON_CodigoChanging(value);
                ReportPropertyChanging("ZON_Codigo");
                _ZON_Codigo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZON_Codigo");
                OnZON_CodigoChanged();
            }
        }
        private global::System.String _ZON_Codigo;
        partial void OnZON_CodigoChanging(global::System.String value);
        partial void OnZON_CodigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PRE_Codigo
        {
            get
            {
                return _PRE_Codigo;
            }
            set
            {
                OnPRE_CodigoChanging(value);
                ReportPropertyChanging("PRE_Codigo");
                _PRE_Codigo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PRE_Codigo");
                OnPRE_CodigoChanged();
            }
        }
        private global::System.String _PRE_Codigo;
        partial void OnPRE_CodigoChanging(global::System.String value);
        partial void OnPRE_CodigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double CLI_Saldo
        {
            get
            {
                return _CLI_Saldo;
            }
            set
            {
                OnCLI_SaldoChanging(value);
                ReportPropertyChanging("CLI_Saldo");
                _CLI_Saldo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CLI_Saldo");
                OnCLI_SaldoChanged();
            }
        }
        private global::System.Double _CLI_Saldo;
        partial void OnCLI_SaldoChanging(global::System.Double value);
        partial void OnCLI_SaldoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double CLI_SaldoDolar
        {
            get
            {
                return _CLI_SaldoDolar;
            }
            set
            {
                OnCLI_SaldoDolarChanging(value);
                ReportPropertyChanging("CLI_SaldoDolar");
                _CLI_SaldoDolar = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CLI_SaldoDolar");
                OnCLI_SaldoDolarChanged();
            }
        }
        private global::System.Double _CLI_SaldoDolar;
        partial void OnCLI_SaldoDolarChanging(global::System.Double value);
        partial void OnCLI_SaldoDolarChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double CLI_MaximoCredito
        {
            get
            {
                return _CLI_MaximoCredito;
            }
            set
            {
                OnCLI_MaximoCreditoChanging(value);
                ReportPropertyChanging("CLI_MaximoCredito");
                _CLI_MaximoCredito = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CLI_MaximoCredito");
                OnCLI_MaximoCreditoChanged();
            }
        }
        private global::System.Double _CLI_MaximoCredito;
        partial void OnCLI_MaximoCreditoChanging(global::System.Double value);
        partial void OnCLI_MaximoCreditoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CLI_Observaciones
        {
            get
            {
                return _CLI_Observaciones;
            }
            set
            {
                OnCLI_ObservacionesChanging(value);
                ReportPropertyChanging("CLI_Observaciones");
                _CLI_Observaciones = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CLI_Observaciones");
                OnCLI_ObservacionesChanged();
            }
        }
        private global::System.String _CLI_Observaciones;
        partial void OnCLI_ObservacionesChanging(global::System.String value);
        partial void OnCLI_ObservacionesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 CLI_ConImpuesto
        {
            get
            {
                return _CLI_ConImpuesto;
            }
            set
            {
                OnCLI_ConImpuestoChanging(value);
                ReportPropertyChanging("CLI_ConImpuesto");
                _CLI_ConImpuesto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CLI_ConImpuesto");
                OnCLI_ConImpuestoChanged();
            }
        }
        private global::System.Int16 _CLI_ConImpuesto;
        partial void OnCLI_ConImpuestoChanging(global::System.Int16 value);
        partial void OnCLI_ConImpuestoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 CLI_DiasCredito
        {
            get
            {
                return _CLI_DiasCredito;
            }
            set
            {
                OnCLI_DiasCreditoChanging(value);
                ReportPropertyChanging("CLI_DiasCredito");
                _CLI_DiasCredito = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CLI_DiasCredito");
                OnCLI_DiasCreditoChanged();
            }
        }
        private global::System.Int16 _CLI_DiasCredito;
        partial void OnCLI_DiasCreditoChanging(global::System.Int16 value);
        partial void OnCLI_DiasCreditoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double CLI_SaldoReporte
        {
            get
            {
                return _CLI_SaldoReporte;
            }
            set
            {
                OnCLI_SaldoReporteChanging(value);
                ReportPropertyChanging("CLI_SaldoReporte");
                _CLI_SaldoReporte = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CLI_SaldoReporte");
                OnCLI_SaldoReporteChanged();
            }
        }
        private global::System.Double _CLI_SaldoReporte;
        partial void OnCLI_SaldoReporteChanging(global::System.Double value);
        partial void OnCLI_SaldoReporteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double CLI_SaldoAdelantos
        {
            get
            {
                return _CLI_SaldoAdelantos;
            }
            set
            {
                OnCLI_SaldoAdelantosChanging(value);
                ReportPropertyChanging("CLI_SaldoAdelantos");
                _CLI_SaldoAdelantos = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CLI_SaldoAdelantos");
                OnCLI_SaldoAdelantosChanged();
            }
        }
        private global::System.Double _CLI_SaldoAdelantos;
        partial void OnCLI_SaldoAdelantosChanging(global::System.Double value);
        partial void OnCLI_SaldoAdelantosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CLI_Activo
        {
            get
            {
                return _CLI_Activo;
            }
            set
            {
                OnCLI_ActivoChanging(value);
                ReportPropertyChanging("CLI_Activo");
                _CLI_Activo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CLI_Activo");
                OnCLI_ActivoChanged();
            }
        }
        private global::System.Int32 _CLI_Activo;
        partial void OnCLI_ActivoChanging(global::System.Int32 value);
        partial void OnCLI_ActivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CLI_Varios
        {
            get
            {
                return _CLI_Varios;
            }
            set
            {
                OnCLI_VariosChanging(value);
                ReportPropertyChanging("CLI_Varios");
                _CLI_Varios = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CLI_Varios");
                OnCLI_VariosChanged();
            }
        }
        private global::System.Int32 _CLI_Varios;
        partial void OnCLI_VariosChanging(global::System.Int32 value);
        partial void OnCLI_VariosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CLI_Clase
        {
            get
            {
                return _CLI_Clase;
            }
            set
            {
                OnCLI_ClaseChanging(value);
                ReportPropertyChanging("CLI_Clase");
                _CLI_Clase = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CLI_Clase");
                OnCLI_ClaseChanged();
            }
        }
        private global::System.String _CLI_Clase;
        partial void OnCLI_ClaseChanging(global::System.String value);
        partial void OnCLI_ClaseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double CLI_CredPendDolares
        {
            get
            {
                return _CLI_CredPendDolares;
            }
            set
            {
                OnCLI_CredPendDolaresChanging(value);
                ReportPropertyChanging("CLI_CredPendDolares");
                _CLI_CredPendDolares = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CLI_CredPendDolares");
                OnCLI_CredPendDolaresChanged();
            }
        }
        private global::System.Double _CLI_CredPendDolares;
        partial void OnCLI_CredPendDolaresChanging(global::System.Double value);
        partial void OnCLI_CredPendDolaresChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double CLI_CredPendColones
        {
            get
            {
                return _CLI_CredPendColones;
            }
            set
            {
                OnCLI_CredPendColonesChanging(value);
                ReportPropertyChanging("CLI_CredPendColones");
                _CLI_CredPendColones = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CLI_CredPendColones");
                OnCLI_CredPendColonesChanged();
            }
        }
        private global::System.Double _CLI_CredPendColones;
        partial void OnCLI_CredPendColonesChanging(global::System.Double value);
        partial void OnCLI_CredPendColonesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double CLI_SaldoRealColones
        {
            get
            {
                return _CLI_SaldoRealColones;
            }
            set
            {
                OnCLI_SaldoRealColonesChanging(value);
                ReportPropertyChanging("CLI_SaldoRealColones");
                _CLI_SaldoRealColones = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CLI_SaldoRealColones");
                OnCLI_SaldoRealColonesChanged();
            }
        }
        private global::System.Double _CLI_SaldoRealColones;
        partial void OnCLI_SaldoRealColonesChanging(global::System.Double value);
        partial void OnCLI_SaldoRealColonesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double CLI_SaldoRealDolares
        {
            get
            {
                return _CLI_SaldoRealDolares;
            }
            set
            {
                OnCLI_SaldoRealDolaresChanging(value);
                ReportPropertyChanging("CLI_SaldoRealDolares");
                _CLI_SaldoRealDolares = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CLI_SaldoRealDolares");
                OnCLI_SaldoRealDolaresChanged();
            }
        }
        private global::System.Double _CLI_SaldoRealDolares;
        partial void OnCLI_SaldoRealDolaresChanging(global::System.Double value);
        partial void OnCLI_SaldoRealDolaresChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CLI_Cliente_Tomo
        {
            get
            {
                return _CLI_Cliente_Tomo;
            }
            set
            {
                OnCLI_Cliente_TomoChanging(value);
                ReportPropertyChanging("CLI_Cliente_Tomo");
                _CLI_Cliente_Tomo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CLI_Cliente_Tomo");
                OnCLI_Cliente_TomoChanged();
            }
        }
        private Nullable<global::System.Int32> _CLI_Cliente_Tomo;
        partial void OnCLI_Cliente_TomoChanging(Nullable<global::System.Int32> value);
        partial void OnCLI_Cliente_TomoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CLI_Cliente_Folio
        {
            get
            {
                return _CLI_Cliente_Folio;
            }
            set
            {
                OnCLI_Cliente_FolioChanging(value);
                ReportPropertyChanging("CLI_Cliente_Folio");
                _CLI_Cliente_Folio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CLI_Cliente_Folio");
                OnCLI_Cliente_FolioChanged();
            }
        }
        private Nullable<global::System.Int32> _CLI_Cliente_Folio;
        partial void OnCLI_Cliente_FolioChanging(Nullable<global::System.Int32> value);
        partial void OnCLI_Cliente_FolioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CLI_Cliente_Asiento
        {
            get
            {
                return _CLI_Cliente_Asiento;
            }
            set
            {
                OnCLI_Cliente_AsientoChanging(value);
                ReportPropertyChanging("CLI_Cliente_Asiento");
                _CLI_Cliente_Asiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CLI_Cliente_Asiento");
                OnCLI_Cliente_AsientoChanged();
            }
        }
        private Nullable<global::System.Int32> _CLI_Cliente_Asiento;
        partial void OnCLI_Cliente_AsientoChanging(Nullable<global::System.Int32> value);
        partial void OnCLI_Cliente_AsientoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CLI_Representa_Nombre
        {
            get
            {
                return _CLI_Representa_Nombre;
            }
            set
            {
                OnCLI_Representa_NombreChanging(value);
                ReportPropertyChanging("CLI_Representa_Nombre");
                _CLI_Representa_Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CLI_Representa_Nombre");
                OnCLI_Representa_NombreChanged();
            }
        }
        private global::System.String _CLI_Representa_Nombre;
        partial void OnCLI_Representa_NombreChanging(global::System.String value);
        partial void OnCLI_Representa_NombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CLI_Representa_Cedula
        {
            get
            {
                return _CLI_Representa_Cedula;
            }
            set
            {
                OnCLI_Representa_CedulaChanging(value);
                ReportPropertyChanging("CLI_Representa_Cedula");
                _CLI_Representa_Cedula = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CLI_Representa_Cedula");
                OnCLI_Representa_CedulaChanged();
            }
        }
        private global::System.String _CLI_Representa_Cedula;
        partial void OnCLI_Representa_CedulaChanging(global::System.String value);
        partial void OnCLI_Representa_CedulaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CLI_Representa_Ocupacion
        {
            get
            {
                return _CLI_Representa_Ocupacion;
            }
            set
            {
                OnCLI_Representa_OcupacionChanging(value);
                ReportPropertyChanging("CLI_Representa_Ocupacion");
                _CLI_Representa_Ocupacion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CLI_Representa_Ocupacion");
                OnCLI_Representa_OcupacionChanged();
            }
        }
        private global::System.String _CLI_Representa_Ocupacion;
        partial void OnCLI_Representa_OcupacionChanging(global::System.String value);
        partial void OnCLI_Representa_OcupacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CLI_Representa_EstadoCivil
        {
            get
            {
                return _CLI_Representa_EstadoCivil;
            }
            set
            {
                OnCLI_Representa_EstadoCivilChanging(value);
                ReportPropertyChanging("CLI_Representa_EstadoCivil");
                _CLI_Representa_EstadoCivil = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CLI_Representa_EstadoCivil");
                OnCLI_Representa_EstadoCivilChanged();
            }
        }
        private global::System.String _CLI_Representa_EstadoCivil;
        partial void OnCLI_Representa_EstadoCivilChanging(global::System.String value);
        partial void OnCLI_Representa_EstadoCivilChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CLI_Representa_Direccion
        {
            get
            {
                return _CLI_Representa_Direccion;
            }
            set
            {
                OnCLI_Representa_DireccionChanging(value);
                ReportPropertyChanging("CLI_Representa_Direccion");
                _CLI_Representa_Direccion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CLI_Representa_Direccion");
                OnCLI_Representa_DireccionChanged();
            }
        }
        private global::System.String _CLI_Representa_Direccion;
        partial void OnCLI_Representa_DireccionChanging(global::System.String value);
        partial void OnCLI_Representa_DireccionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CLI_Garante_Nombre
        {
            get
            {
                return _CLI_Garante_Nombre;
            }
            set
            {
                OnCLI_Garante_NombreChanging(value);
                ReportPropertyChanging("CLI_Garante_Nombre");
                _CLI_Garante_Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CLI_Garante_Nombre");
                OnCLI_Garante_NombreChanged();
            }
        }
        private global::System.String _CLI_Garante_Nombre;
        partial void OnCLI_Garante_NombreChanging(global::System.String value);
        partial void OnCLI_Garante_NombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CLI_Garante_Cedula
        {
            get
            {
                return _CLI_Garante_Cedula;
            }
            set
            {
                OnCLI_Garante_CedulaChanging(value);
                ReportPropertyChanging("CLI_Garante_Cedula");
                _CLI_Garante_Cedula = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CLI_Garante_Cedula");
                OnCLI_Garante_CedulaChanged();
            }
        }
        private global::System.String _CLI_Garante_Cedula;
        partial void OnCLI_Garante_CedulaChanging(global::System.String value);
        partial void OnCLI_Garante_CedulaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CLI_Fiador_Nombre
        {
            get
            {
                return _CLI_Fiador_Nombre;
            }
            set
            {
                OnCLI_Fiador_NombreChanging(value);
                ReportPropertyChanging("CLI_Fiador_Nombre");
                _CLI_Fiador_Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CLI_Fiador_Nombre");
                OnCLI_Fiador_NombreChanged();
            }
        }
        private global::System.String _CLI_Fiador_Nombre;
        partial void OnCLI_Fiador_NombreChanging(global::System.String value);
        partial void OnCLI_Fiador_NombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CLI_Fiador_Tomo
        {
            get
            {
                return _CLI_Fiador_Tomo;
            }
            set
            {
                OnCLI_Fiador_TomoChanging(value);
                ReportPropertyChanging("CLI_Fiador_Tomo");
                _CLI_Fiador_Tomo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CLI_Fiador_Tomo");
                OnCLI_Fiador_TomoChanged();
            }
        }
        private Nullable<global::System.Int32> _CLI_Fiador_Tomo;
        partial void OnCLI_Fiador_TomoChanging(Nullable<global::System.Int32> value);
        partial void OnCLI_Fiador_TomoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CLI_Fiador_Folio
        {
            get
            {
                return _CLI_Fiador_Folio;
            }
            set
            {
                OnCLI_Fiador_FolioChanging(value);
                ReportPropertyChanging("CLI_Fiador_Folio");
                _CLI_Fiador_Folio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CLI_Fiador_Folio");
                OnCLI_Fiador_FolioChanged();
            }
        }
        private Nullable<global::System.Int32> _CLI_Fiador_Folio;
        partial void OnCLI_Fiador_FolioChanging(Nullable<global::System.Int32> value);
        partial void OnCLI_Fiador_FolioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CLI_Fiador_Asiento
        {
            get
            {
                return _CLI_Fiador_Asiento;
            }
            set
            {
                OnCLI_Fiador_AsientoChanging(value);
                ReportPropertyChanging("CLI_Fiador_Asiento");
                _CLI_Fiador_Asiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CLI_Fiador_Asiento");
                OnCLI_Fiador_AsientoChanged();
            }
        }
        private Nullable<global::System.Int32> _CLI_Fiador_Asiento;
        partial void OnCLI_Fiador_AsientoChanging(Nullable<global::System.Int32> value);
        partial void OnCLI_Fiador_AsientoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CLI_Fiador_Representa_Nombre
        {
            get
            {
                return _CLI_Fiador_Representa_Nombre;
            }
            set
            {
                OnCLI_Fiador_Representa_NombreChanging(value);
                ReportPropertyChanging("CLI_Fiador_Representa_Nombre");
                _CLI_Fiador_Representa_Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CLI_Fiador_Representa_Nombre");
                OnCLI_Fiador_Representa_NombreChanged();
            }
        }
        private global::System.String _CLI_Fiador_Representa_Nombre;
        partial void OnCLI_Fiador_Representa_NombreChanging(global::System.String value);
        partial void OnCLI_Fiador_Representa_NombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CLI_Fiador_Representa_Cedula
        {
            get
            {
                return _CLI_Fiador_Representa_Cedula;
            }
            set
            {
                OnCLI_Fiador_Representa_CedulaChanging(value);
                ReportPropertyChanging("CLI_Fiador_Representa_Cedula");
                _CLI_Fiador_Representa_Cedula = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CLI_Fiador_Representa_Cedula");
                OnCLI_Fiador_Representa_CedulaChanged();
            }
        }
        private global::System.String _CLI_Fiador_Representa_Cedula;
        partial void OnCLI_Fiador_Representa_CedulaChanging(global::System.String value);
        partial void OnCLI_Fiador_Representa_CedulaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VEN_Vendedor_Alquileres
        {
            get
            {
                return _VEN_Vendedor_Alquileres;
            }
            set
            {
                OnVEN_Vendedor_AlquileresChanging(value);
                ReportPropertyChanging("VEN_Vendedor_Alquileres");
                _VEN_Vendedor_Alquileres = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VEN_Vendedor_Alquileres");
                OnVEN_Vendedor_AlquileresChanged();
            }
        }
        private global::System.String _VEN_Vendedor_Alquileres;
        partial void OnVEN_Vendedor_AlquileresChanging(global::System.String value);
        partial void OnVEN_Vendedor_AlquileresChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VEN_Vendedor_Servicios
        {
            get
            {
                return _VEN_Vendedor_Servicios;
            }
            set
            {
                OnVEN_Vendedor_ServiciosChanging(value);
                ReportPropertyChanging("VEN_Vendedor_Servicios");
                _VEN_Vendedor_Servicios = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VEN_Vendedor_Servicios");
                OnVEN_Vendedor_ServiciosChanged();
            }
        }
        private global::System.String _VEN_Vendedor_Servicios;
        partial void OnVEN_Vendedor_ServiciosChanging(global::System.String value);
        partial void OnVEN_Vendedor_ServiciosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cli_Administrativo
        {
            get
            {
                return _cli_Administrativo;
            }
            set
            {
                Oncli_AdministrativoChanging(value);
                ReportPropertyChanging("cli_Administrativo");
                _cli_Administrativo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cli_Administrativo");
                Oncli_AdministrativoChanged();
            }
        }
        private global::System.Int32 _cli_Administrativo;
        partial void Oncli_AdministrativoChanging(global::System.Int32 value);
        partial void Oncli_AdministrativoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cli_Judicial
        {
            get
            {
                return _cli_Judicial;
            }
            set
            {
                Oncli_JudicialChanging(value);
                ReportPropertyChanging("cli_Judicial");
                _cli_Judicial = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cli_Judicial");
                Oncli_JudicialChanged();
            }
        }
        private global::System.Int32 _cli_Judicial;
        partial void Oncli_JudicialChanging(global::System.Int32 value);
        partial void Oncli_JudicialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] timestamp
        {
            get
            {
                return StructuralObject.GetValidValue(_timestamp);
            }
            set
            {
                OntimestampChanging(value);
                ReportPropertyChanging("timestamp");
                _timestamp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("timestamp");
                OntimestampChanged();
            }
        }
        private global::System.Byte[] _timestamp;
        partial void OntimestampChanging(global::System.Byte[] value);
        partial void OntimestampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String USR_Usuario_Modificacion
        {
            get
            {
                return _USR_Usuario_Modificacion;
            }
            set
            {
                OnUSR_Usuario_ModificacionChanging(value);
                ReportPropertyChanging("USR_Usuario_Modificacion");
                _USR_Usuario_Modificacion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("USR_Usuario_Modificacion");
                OnUSR_Usuario_ModificacionChanged();
            }
        }
        private global::System.String _USR_Usuario_Modificacion;
        partial void OnUSR_Usuario_ModificacionChanging(global::System.String value);
        partial void OnUSR_Usuario_ModificacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> USR_Fecha_Modificacion
        {
            get
            {
                return _USR_Fecha_Modificacion;
            }
            set
            {
                OnUSR_Fecha_ModificacionChanging(value);
                ReportPropertyChanging("USR_Fecha_Modificacion");
                _USR_Fecha_Modificacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("USR_Fecha_Modificacion");
                OnUSR_Fecha_ModificacionChanged();
            }
        }
        private Nullable<global::System.DateTime> _USR_Fecha_Modificacion;
        partial void OnUSR_Fecha_ModificacionChanging(Nullable<global::System.DateTime> value);
        partial void OnUSR_Fecha_ModificacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String USR_Usuario_Inclusion
        {
            get
            {
                return _USR_Usuario_Inclusion;
            }
            set
            {
                OnUSR_Usuario_InclusionChanging(value);
                ReportPropertyChanging("USR_Usuario_Inclusion");
                _USR_Usuario_Inclusion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("USR_Usuario_Inclusion");
                OnUSR_Usuario_InclusionChanged();
            }
        }
        private global::System.String _USR_Usuario_Inclusion;
        partial void OnUSR_Usuario_InclusionChanging(global::System.String value);
        partial void OnUSR_Usuario_InclusionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> USR_Fecha_Inclusion
        {
            get
            {
                return _USR_Fecha_Inclusion;
            }
            set
            {
                OnUSR_Fecha_InclusionChanging(value);
                ReportPropertyChanging("USR_Fecha_Inclusion");
                _USR_Fecha_Inclusion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("USR_Fecha_Inclusion");
                OnUSR_Fecha_InclusionChanged();
            }
        }
        private Nullable<global::System.DateTime> _USR_Fecha_Inclusion;
        partial void OnUSR_Fecha_InclusionChanging(Nullable<global::System.DateTime> value);
        partial void OnUSR_Fecha_InclusionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CLI_Tipo
        {
            get
            {
                return _CLI_Tipo;
            }
            set
            {
                OnCLI_TipoChanging(value);
                ReportPropertyChanging("CLI_Tipo");
                _CLI_Tipo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CLI_Tipo");
                OnCLI_TipoChanged();
            }
        }
        private global::System.String _CLI_Tipo;
        partial void OnCLI_TipoChanging(global::System.String value);
        partial void OnCLI_TipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COB_Cobrador
        {
            get
            {
                return _COB_Cobrador;
            }
            set
            {
                OnCOB_CobradorChanging(value);
                ReportPropertyChanging("COB_Cobrador");
                _COB_Cobrador = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("COB_Cobrador");
                OnCOB_CobradorChanged();
            }
        }
        private global::System.String _COB_Cobrador;
        partial void OnCOB_CobradorChanging(global::System.String value);
        partial void OnCOB_CobradorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CLI_Pago
        {
            get
            {
                return _CLI_Pago;
            }
            set
            {
                OnCLI_PagoChanging(value);
                ReportPropertyChanging("CLI_Pago");
                _CLI_Pago = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CLI_Pago");
                OnCLI_PagoChanged();
            }
        }
        private global::System.String _CLI_Pago;
        partial void OnCLI_PagoChanging(global::System.String value);
        partial void OnCLI_PagoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CON_DESCUENTO_AUTORIZA
        {
            get
            {
                return _CON_DESCUENTO_AUTORIZA;
            }
            set
            {
                OnCON_DESCUENTO_AUTORIZAChanging(value);
                ReportPropertyChanging("CON_DESCUENTO_AUTORIZA");
                _CON_DESCUENTO_AUTORIZA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CON_DESCUENTO_AUTORIZA");
                OnCON_DESCUENTO_AUTORIZAChanged();
            }
        }
        private Nullable<global::System.Int32> _CON_DESCUENTO_AUTORIZA;
        partial void OnCON_DESCUENTO_AUTORIZAChanging(Nullable<global::System.Int32> value);
        partial void OnCON_DESCUENTO_AUTORIZAChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OuterModel", Name="ResourceSource")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ResourceSource : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ResourceSource object.
        /// </summary>
        /// <param name="code">Initial value of the Code property.</param>
        /// <param name="balance">Initial value of the Balance property.</param>
        /// <param name="rType">Initial value of the RType property.</param>
        /// <param name="cost">Initial value of the Cost property.</param>
        /// <param name="taxed">Initial value of the Taxed property.</param>
        public static ResourceSource CreateResourceSource(global::System.String code, global::System.Double balance, global::System.String rType, global::System.Double cost, global::System.Int16 taxed)
        {
            ResourceSource resourceSource = new ResourceSource();
            resourceSource.Code = code;
            resourceSource.Balance = balance;
            resourceSource.RType = rType;
            resourceSource.Cost = cost;
            resourceSource.Taxed = taxed;
            return resourceSource;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                if (_Code != value)
                {
                    OnCodeChanging(value);
                    ReportPropertyChanging("Code");
                    _Code = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Code");
                    OnCodeChanged();
                }
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Balance
        {
            get
            {
                return _Balance;
            }
            set
            {
                if (_Balance != value)
                {
                    OnBalanceChanging(value);
                    ReportPropertyChanging("Balance");
                    _Balance = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Balance");
                    OnBalanceChanged();
                }
            }
        }
        private global::System.Double _Balance;
        partial void OnBalanceChanging(global::System.Double value);
        partial void OnBalanceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RType
        {
            get
            {
                return _RType;
            }
            set
            {
                if (_RType != value)
                {
                    OnRTypeChanging(value);
                    ReportPropertyChanging("RType");
                    _RType = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("RType");
                    OnRTypeChanged();
                }
            }
        }
        private global::System.String _RType;
        partial void OnRTypeChanging(global::System.String value);
        partial void OnRTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Cost
        {
            get
            {
                return _Cost;
            }
            set
            {
                if (_Cost != value)
                {
                    OnCostChanging(value);
                    ReportPropertyChanging("Cost");
                    _Cost = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Cost");
                    OnCostChanged();
                }
            }
        }
        private global::System.Double _Cost;
        partial void OnCostChanging(global::System.Double value);
        partial void OnCostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Taxed
        {
            get
            {
                return _Taxed;
            }
            set
            {
                if (_Taxed != value)
                {
                    OnTaxedChanging(value);
                    ReportPropertyChanging("Taxed");
                    _Taxed = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Taxed");
                    OnTaxedChanged();
                }
            }
        }
        private global::System.Int16 _Taxed;
        partial void OnTaxedChanging(global::System.Int16 value);
        partial void OnTaxedChanged();

        #endregion
    
    }

    #endregion
    
}
